### ISSUE TITLE
Input colorspace

### ISSUE THREAD

**Issue by elmuz** [ildoonet/tf-pose-estimation#102]
Can you confirm the network is trained to work in OpenCV default colorspace (BGR) instead of usual RGB? I couldn't see any conversion, neither in run_webcam.py nor in estimator.py, so I assume it stays in BGR format up to the network input...

**Comment by yw155** [comment]
Hi @ildoonet, I also noticed that there is no such a conversion from BGR to RGB in the training and test codes. But the original CMU-COCO caffe model is in the format of RGB. So is it possible that this conversion affects the last training performance?

**Comment by ildoonet** [comment]
@yw155 yeah it could harm the performance. I will change it. Thanks.
