### ISSUE TITLE
How to get KeyPoint (x, y) ?

### ISSUE THREAD

**Issue by nueng000** [ildoonet/tf-pose-estimation#104]
I tried to find example code but I didn't see it.

I want to get keypoint in realtime (run with webcam).

Thank you.

PS. Can we detect hand and face (same original repo)?

**Comment by yw155** [comment]
Hi @nueng000, actually you can find such an output from the function of 'draw_humans()' in the file of src/estimator.py, as shown below, where body_part.x and .y are the coordinates of keypoints. You can imitate this function and write some codes by yourself and it should be easy to obtain what you want. Thanks.

def draw_humans(npimg, humans, imgcopy=False):
if imgcopy:
npimg = np.copy(npimg)
image_h, image_w = npimg.shape[:2]
centers = {}
for human in humans:
# draw point
for i in range(common.CocoPart.Background.value):
if i not in human.body_parts.keys():
continue

             body_part = human.body_parts[i]
             center = (int(body_part.x * image_w + 0.5), int(body_part.y * image_h + 0.5))

**Comment by yw155** [comment]
Hi @nueng000, actually you can find such an output from the function of 'draw_humans()' in the file of src/estimator.py, as shown below, where body_part.x and .y are the coordinates of keypoints. You can imitate this function and write some codes by yourself and it should be easy to obtain what you want. Thanks.
`Hi @techjjun, actually you can find such an output from the function of 'draw_humans()' in the file of src/estimator.py, as shown below, where body_part.x and .y are the coordinates of keypoints. You can imitate this function and write some codes by yourself and it should be easy to obtain what you want. Thanks.

def draw_humans(npimg, humans, imgcopy=False):
if imgcopy:
npimg = np.copy(npimg)
image_h, image_w = npimg.shape[:2]
centers = {}
for human in humans:
# draw point
for i in range(common.CocoPart.Background.value):
if i not in human.body_parts.keys():
continue

             body_part = human.body_parts[i]
             center = (int(body_part.x * image_w + 0.5), int(body_part.y * image_h + 0.5))`
     def draw_humans(npimg, humans, imgcopy=False):
          if imgcopy:
          npimg = np.copy(npimg)
image_h, image_w = npimg.shape[:2]
centers = {}
for human in humans:
# draw point
for i in range(common.CocoPart.Background.value):
if i not in human.body_parts.keys():
             continue

             body_part = human.body_parts[i]
             center = (int(body_part.x * image_w + 0.5), int(body_part.y * image_h + 0.5))
