### ISSUE TITLE
path errors in files in src dir 

### ISSUE THREAD

**Issue by Armen001** [ildoonet/tf-pose-estimation#105]
I get an error from this rows.
https://github.com/ildoonet/tf-pose-estimation/blob/master/src/common.py#L122-L133
I think you should change paths from './images/p1.jpg' to '../images/p1.jpg'

This kind of error exist in https://github.com/ildoonet/tf-pose-estimation/blob/master/src/networks.py#L12

We think in src this kind of errors exist.

**Comment by ildoonet** [comment]
I run train.py outside 'src' folder like below.

python3 ./src/train.py ...
