### ISSUE TITLE
thread errror during training 

### ISSUE THREAD

**Issue by Armen001** [ildoonet/tf-pose-estimation#106]
When running this code 
"python3 train.py --datapath ../../annotations/annotations --batchsize=64 --lr=0.001 --modelpath bla --imgpath ../../images/"
I get this errror 
"File "train.py", line 74, in <module>
    enqueuer = DataFlowToQueue(df, [input_node, heatmap_node, vectmap_node], queue_size=100)
  File "/home/armen/Workspace/tf-pose-estimation/src/pose_dataset.py", line 395, in __init__
    self.daemon = True
  File "/usr/lib/python3.6/threading.py", line 1139, in daemon
    raise RuntimeError("Thread.__init__() not called")
RuntimeError: Thread.__init__() not called"

I fixed this problem by changing line 
https://github.com/ildoonet/tf-pose-estimation/blob/master/src/pose_dataset.py#L392 with line 
"super(DataFlowToQueue, self).__init__()"

**Comment by scyoyo** [comment]
I fixed it by adding  `threading.Thread.__init__(self)` before `self.daemon=true`

**Comment by shubjain26** [comment]
@scyoyo 
was getting same error, after that I'm getting another error : 

```
Traceback (most recent call last):
  File "src/train.py", line 197, in <module>
    enqueuer.start()
  File "/home/tf-pose-estimation/src/pose_dataset.py", line 423, in start
    super(DataFlowToQueue).start()
AttributeError: 'super' object has no attribute 'start
```'

**Comment by ildoonet** [comment]
Thanks. I add 

super().__init__()

Since this repo supports only python3.

Thanks.
