### ISSUE TITLE
Error when running train.py

### ISSUE THREAD

**Issue by Armen001** [ildoonet/tf-pose-estimation#107]
when I run the train.py by 
python3 train.py --datapath ../../annotations/annotations --batchsize=64 --lr=0.001 --modelpath bla --imgpath ../../images/
after printing out the below info 
[2018-02-28 13:19:19,630] [train] [INFO] Restore pretrained weights...
the following errors occur: 
2018-02-28 13:19:24.316570: W tensorflow/core/framework/op_kernel.cc:1198] Data loss: not an sstable (bad magic number)
........
Traceback (most recent call last):
  File "/home/armen/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/armen/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/armen/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

And when we run the train.py with the  "--model=cmu" flag:
python3 train.py --model=cmu --datapath ../../annotations/annotations --batchsize=64 --lr=0.001 --modelpath bla --imgpath ../../images/
we get this error
OSError: Failed to interpret file '../models/numpy/openpose_coco.npy' as a pickle
@ildoonet  is it familiar to you?

**Comment by ouceduxzk** [comment]
check your openpose_coco.npy file, is it valid ?

**Comment by ouceduxzk** [comment]
its a npy file,  a big one, if you just download it in one second, then it probably means you are not downloading the correct file, please have some common knowledge about a weight file, and try to solve such simple problems by yourself, for example, check the url in download.sh , paste into your brower and download that way, does it make any difference? then if it is , it means your file is downloaded wrong. Otherwise, it is some other problem. That's how people solve easy problems before asking

**Comment by scyoyo** [comment]
I also meet with this problem and waste one day to solve that. The thing is that `wget` in downlaod.sh doesn't work on mediafire.com but it will create a fake file that looks like working. Hope the author could fix this bug.

**Comment by ouceduxzk** [comment]
I like the buggy code here, people needs to solve those small problems themselves, which are not that hard and they can also avoid that in their own code

**Comment by Armen001** [comment]
Sorry for my english. I am a student and just getting experience in the domain. Though I finally was able to train. Thanks a lot @ouceduxzk ouceduxzk, you were rigth. The openpose_coco.npy was not valid, it was an html file. The error wich I get from mobilenet was again from the same mistake.

**Comment by daisukelab** [comment]
Summarizing here so that no more people lost by the download.sh...
1. Open your browser.
2. Copy and paste following address to your browser, one by one.
3. You will see DOWNLOAD button on the page, just click and download...

```
http://www.mediafire.com/file/kibz0x9e7h11ueb/mobilenet_v1_0.75_224.ckpt.data-00000-of-00001
http://www.mediafire.com/file/t8909eaikvc6ea2/mobilenet_v1_0.75_224.ckpt.index
http://www.mediafire.com/file/6jjnbn1aged614x/mobilenet_v1_0.75_224.ckpt.meta
```
