### ISSUE TITLE
How can I get the outputs??

### ISSUE THREAD

**Issue by techjjun** [ildoonet/tf-pose-estimation#111]
In openpose c++ API  I can get an outputs of keypoint coordinates with body part.

Can i get the same outputs in here tensorflow version??

**Comment by yw155** [comment]
Hi @techjjun, actually you can find such an output from the function of 'draw_humans()' in the file of src/estimator.py, as shown below, where body_part.x and .y are the coordinates of keypoints. You can imitate this function and write some codes by yourself and it should be easy to obtain what you want. Thanks.

def draw_humans(npimg, humans, imgcopy=False):
        if imgcopy:
            npimg = np.copy(npimg)
        image_h, image_w = npimg.shape[:2]
        centers = {}
        for human in humans:
            # draw point
            for i in range(common.CocoPart.Background.value):
                if i not in human.body_parts.keys():
                    continue

                body_part = human.body_parts[i]
                center = (int(body_part.x * image_w + 0.5), int(body_part.y * image_h + 0.5))

**Comment by yw155** [comment]
Closes #111

**Comment by techjjun** [comment]
Thanks for the comment!

**Comment by eugenpopescu23** [comment]
Hi, I don't have much experience with any of this, but I really need to know how to do that, can someone please show me and explain to me how to do it, i need the outputs and then compare them! It would be really helpful please! thanks

**Comment by ildoonet** [comment]
Close since there is an appropriate answer.
