### ISSUE TITLE
How to get the full environment source and codes? from docker and Dockerfile?

### ISSUE THREAD

**Issue by Ai-is-light** [ildoonet/tf-pose-estimation#115]
I ran
 docker build --tag idock.daumkakao.io/kakaobrain/deepcloud-sshd:openpose-preprocess -f ./docker/Dockerfile .
but 
Downloading AST-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ge2_f1ih/ast/setup.py", line 6, in <module>
        README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
      File "/usr/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-ge2_f1ih/ast/AST/README'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ge2_f1ih/ast/
The command '/bin/sh -c cd /root/tf-openpose/ && pip3 install -U setuptools && pip3 install tensorflow && pip3 install -r requirements.txt' returned a non-zero code: 1

looking forward any suggestion. Thanks @leighton @ildoonet

**Comment by GajjarMihir** [comment]
#127 This works.
