### ISSUE TITLE
Available Models

### ISSUE THREAD

**Issue by grkem1** [ildoonet/tf-pose-estimation#117]
Hello,

In models section, 5 models are mentioned, which are cmu, dsconv and mobilenet variants(mobilenet, mobilenet_fast and mobilenet_accurate). However 2 graph files are provided which are cmu and mobilenet_thin. Are the other models also available?

**Comment by s101010tw** [comment]
Hi @ildoonet 

I have the same question as @grkem1
Could you share the other models to us?

Thanks

**Comment by ildoonet** [comment]
I will upload new models as soon as It is ready. No specific due date yet.
