### ISSUE TITLE
How can we use hand detector from OpenPose

### ISSUE THREAD

**Issue by oakkas** [ildoonet/tf-pose-estimation#123]
Thanks for sharing this great work.
I am working on  a project that relies on pose estimation and  hand landmarks estimation. I was wondering if hand detector from OpenPose can also be used within your tensorflow version.

Thanks

**Comment by gkswamy98** [comment]
I have the same question - any updates?

**Comment by oakkas** [comment]
@gkswamy98 
Not on my end yet.

**Comment by ildoonet** [comment]
There is no plan for this.
