### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/scratch/tmp/pip-build-90_x8_4d/ast/AST/README'

### ISSUE THREAD

**Issue by monajalal** [ildoonet/tf-pose-estimation#127]
pip install -r requirements.txt
Collecting git+https://github.com/ppwwyyxx/tensorpack.git (from -r requirements.txt (line 9))
  Cloning https://github.com/ppwwyyxx/tensorpack.git to /scratch/tmp/pip-1tjujgfg-build
Requirement already satisfied: argparse in /scratch/sjn/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: matplotlib in /scratch/sjn/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: scipy in /scratch/sjn/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: tqdm in /scratch/sjn/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests in /scratch/sjn/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Collecting fire (from -r requirements.txt (line 6))
  Using cached fire-0.1.3.tar.gz
Collecting ast (from -r requirements.txt (line 7))
  Using cached AST-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/tmp/pip-build-90_x8_4d/ast/setup.py", line 6, in <module>
        README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
      File "/scratch/sjn/anaconda/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/scratch/tmp/pip-build-90_x8_4d/ast/AST/README'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /scratch/tmp/pip-build-90_x8_4d/ast/
[jalal@goku tf-openpose]$

**Comment by monajalal** [comment]
possibly this is the solution 
https://github.com/ildoonet/tf-pose-estimation/issues/96

**Comment by GajjarMihir** [comment]
Yes, I tried that solution. The code works perfectly fine.
