### ISSUE TITLE
Train and test problem

### ISSUE THREAD

**Issue by GhadeerMohamad** [ildoonet/tf-pose-estimation#128]
I am having this error straight away.
python3 run.py or train.py  
Illegal instruction (core dumped)
Working on Ubuntu 17.10 and python3

**Comment by ildoonet** [comment]
I don't know the reason. You should check your core dumped file. 
Currently source codes works fine.

**Comment by rawandeheliah** [comment]
?\@GhadeerMohamad  did you know the reason for that problem ?
i get :
"ASSERT: "false" in file qasciikey.cpp, line 501
Aborted (core dumped)"
 when i write : 
python3 run_video.py  --video=vid1.mp4
