### ISSUE TITLE
ValueError: No op named SSTableReaderV2 in defined operations.

### ISSUE THREAD

**Issue by jeyawn** [ildoonet/tf-pose-estimation#13]
I tried to freeze the model and run it in android. But I found that when I called import_meta_graph, it replied some errors,
ValueError: No op named SSTableReaderV2 in defined operations.
Is anyone successful export the module"?

**Comment by ildoonet** [comment]
@jeyawn 

I just uploaded graph files. And they work just fine on many platforms I tested. 

You can download graph files and test on your machine. If your problem persist, please check your commands to export. 

I'm closing it since this questions is not related this repo.

**Comment by GajjarMihir** [comment]
@jeyawn @ildoonet If anybody is able to run openpose on android then please help me with the same. It would be really helpful for me.

**Comment by jeyawn** [comment]
It is ok to run the model in android platform.

**Comment by GajjarMihir** [comment]
Ohh I have been trying to implement it on Android. Were you able to successfully do so?
