### ISSUE TITLE
KeyError: 'mobilenet_thin_432x368'

### ISSUE THREAD

**Issue by lenixlobo** [ildoonet/tf-pose-estimation#130]
Not able to run the above model?
python src/run_webcam.py --model=mobilenet_thin_432x368 --camera=0
Traceback (most recent call last):
  File "src/run_webcam.py", line 32, in <module>
    logger.debug('initialization %s : %s' % (args.model, get_graph_path(args.model)))
   graph_path = dyn_graph_path[model_name]
KeyError: 'mobilenet_thin_432x368'

**Comment by Aileenlingyu** [comment]
You might need to use mobilenet_thin, check whether you actually have 'mobilenet_thin_432x368' in your dyn_graph_path function

**Comment by lenixlobo** [comment]
i am able to run it but it gets stuck at Adding gpus

**Comment by intissarkh** [comment]
hii want to know how i resolve this problem ti is the same error for me

**Comment by taizhehui** [comment]
hii did you solve the problem?
