### ISSUE TITLE
Where is the real-time coordinate values?

### ISSUE THREAD

**Issue by Sad7Dayz** [ildoonet/tf-pose-estimation#133]
I ask a Question.
where is Coordinate value? and I want to save the coordinate values externally.

**Comment by ildoonet** [comment]
After run 'inference' function, you will get a list of 'Human' Objects.

All the informations are inside there.

**Comment by priyakansal** [comment]
@ildoonet 
When I am running the inference function, i am getting an empty list of humans.
I ran the following code for a sample image:
     e = TfPoseEstimator(get_graph_path(model_name="mobilenet_thin"),target_size=(432, 368))
     image = common.read_imgfile("/Users/priyakansal/Downloads/tf-openpose/images/hand1_small.jpg", None, None)
    humans = e.inference(image)
    humans
    []

Please suggest why I am not getting coordinates?

**Comment by Alexfinkelshtein** [comment]
@priyakansal  I am getting the same thing :\
