### ISSUE TITLE
save the estimated video

### ISSUE THREAD

**Issue by guofuzheng** [ildoonet/tf-pose-estimation#140]
i want to save the estimated video without the original background just the skeleton ,what should i do?

**Comment by AVCarreiro** [comment]
In src/estimator.py you have a class TFPoseEstimator with the method draw_humans which takes an image as input. Simply pass an empty image (all zeros) and you get an image with only the skeleton overlaid.

**Comment by guofuzheng** [comment]
@AVCarreiro  hello,i want to get the output like this
<img width="680" alt="2018-04-13 9 49 05" src="https://user-images.githubusercontent.com/25239334/38713341-473eea04-3f03-11e8-9c4d-243ceeffa1ad.png">
and i modify the src/run_video.py like this
<img width="898" alt="2018-04-13 9 53 04" src="https://user-images.githubusercontent.com/25239334/38713388-7ed6835a-3f03-11e8-826e-493162cc0bea.png">
i replace the original input "image" with "test". But i get the wrong output ,may i ask for your help?
<img width="568" alt="2018-04-13 10 03 50" src="https://user-images.githubusercontent.com/25239334/38713412-9de5082a-3f03-11e8-9736-c3336c3b063a.png">

**Comment by AVCarreiro** [comment]
Seems like you have an issue with the image shape, or the dtype. I think opencv expects images as matrices of type 'uint8'.

**Comment by guofuzheng** [comment]
@AVCarreiro  I have solved the problem.Thank you for your help.

**Comment by rawandeheliah** [comment]
@guofuzheng  could you provide me please with code for saving the estimated video ?

**Comment by guofuzheng** [comment]
@rawandeheliah hello, i did not save the estimated video, i saved the estimated pictures. The code can process videos also can process pictures. About how to save the estimated pictures,  it is very easy. Let me show you the code. 
```
humans = e.inference(image)
image = TfPoseEstimator.draw_humans(image, humans, imgcopy=True)
# cv2.imshow('tf-pose-estimation result', image)
cv2.imwrite(path_save+tmp.split('.')[0]+'/'+str(i)+'.jpg',image)
```
'image' is the image you want to estimate.  After the second line of the code, and if we use 'cv2.imshow' the code will show us the estimated image, if we use'cv2.imwrite' , the code will save the estimated image. If you have any problem about how to save the estimated image, just let me know.
