### ISSUE TITLE
Extracting the coordinates from the output of "Openpose/concat_stage7" node in android

### ISSUE THREAD

**Issue by GajjarMihir** [ildoonet/tf-pose-estimation#146]
I used the graph_freeze.pb file of cmu model and was able to get the output of "Openpose/concat_stage7" node in to an array of size 46×46×57 as the size of my input image is 368×368. I have implemented the code in android.

In python I was able to extract the coordinates from the output of the model using the below code:

'''
    humans = e.inference(image, scales=scales)

    for human in humans:
	# draw point
	    for i in range(common.CocoPart.Background.value):
	        if i not in human.body_parts.keys():
	       	    continue
	       	print(human.body_parts[i])

'''

It gives the coordinates of the body parts along with the score. The output is as follows:
BodyPart:0-(0.61, 0.24) score=5.18
BodyPart:1-(0.61, 0.33) score=5.55
BodyPart:2-(0.65, 0.35) score=6.24
BodyPart:3-(0.70, 0.33) score=7.71
BodyPart:4-(0.74, 0.30) score=7.71
BodyPart:5-(0.56, 0.30) score=3.84
BodyPart:6-(0.48, 0.24) score=6.76
BodyPart:7-(0.39, 0.24) score=6.76
BodyPart:8-(0.59, 0.57) score=6.38
BodyPart:9-(0.61, 0.70) score=9.60
BodyPart:10-(0.69, 0.83) score=9.60
BodyPart:11-(0.56, 0.57) score=7.44
BodyPart:12-(0.46, 0.72) score=9.11
BodyPart:13-(0.44, 0.89) score=9.11
BodyPart:15-(0.63, 0.22) score=5.61
BodyPart:17-(0.65, 0.24) score=3.84

I want to get these coordinates in android. I already have the output of the "Openpose/concat_stage7" node which is 46×46×57. It would be great if anyone can help me with this.

I can share my Android code.

**Comment by ildoonet** [comment]
@GajjarMihir 

The post processing part should be implemented in java or c++ to be run on android devices. 

I have a plan to develop c++ version. If you share your android code, It will be very helpful.

**Comment by GajjarMihir** [comment]
@ildoonet Sure. I can share my android code. How should I share?

**Comment by ildoonet** [comment]
@GajjarMihir Can you share it via github or send it to my email

ildoo@ildoo.net

**Comment by SujtihChristopher** [comment]
> I used the graph_freeze.pb file of cmu model and was able to get the output of "Openpose/concat_stage7" node in to an array of size 46×46×57 as the size of my input image is 368×368. I have implemented the code in android.
> 
> In python I was able to extract the coordinates from the output of the model using the below code:
> 
> '''
> humans = e.inference(image, scales=scales)
> 
> ```
> for human in humans:
> # draw point
>     for i in range(common.CocoPart.Background.value):
>         if i not in human.body_parts.keys():
>        	    continue
>        	print(human.body_parts[i])
> ```
> 
> '''
> 
> It gives the coordinates of the body parts along with the score. The output is as follows:
> BodyPart:0-(0.61, 0.24) score=5.18
> BodyPart:1-(0.61, 0.33) score=5.55
> BodyPart:2-(0.65, 0.35) score=6.24
> BodyPart:3-(0.70, 0.33) score=7.71
> BodyPart:4-(0.74, 0.30) score=7.71
> BodyPart:5-(0.56, 0.30) score=3.84
> BodyPart:6-(0.48, 0.24) score=6.76
> BodyPart:7-(0.39, 0.24) score=6.76
> BodyPart:8-(0.59, 0.57) score=6.38
> BodyPart:9-(0.61, 0.70) score=9.60
> BodyPart:10-(0.69, 0.83) score=9.60
> BodyPart:11-(0.56, 0.57) score=7.44
> BodyPart:12-(0.46, 0.72) score=9.11
> BodyPart:13-(0.44, 0.89) score=9.11
> BodyPart:15-(0.63, 0.22) score=5.61
> BodyPart:17-(0.65, 0.24) score=3.84
> 
> I want to get these coordinates in android. I already have the output of the "Openpose/concat_stage7" node which is 46×46×57. It would be great if anyone can help me with this.
> 
> I can share my Android code.

How to relate these coordinates to pixel position?
