### ISSUE TITLE
get the 3d  coordinate of the keypoint

### ISSUE THREAD

**Issue by guofuzheng** [ildoonet/tf-pose-estimation#147]
I want to get the 3d coordinate of the keypoint , what should i do?

**Comment by gregoireandre** [comment]
You should get a look at this repo which use tf implementation of openpose to feed a SH network and get the 3d coordinates of the full body
https://github.com/ArashHosseini/3d-pose-baseline

**Comment by ildoonet** [comment]
@gregoireandre Thanks for the reply!
@guofuzheng Thanks for the interest. I have a no plan for 3d points for now. I'm closing this issue.
