### ISSUE TITLE
heatmap generation

### ISSUE THREAD

**Issue by boldjoel** [ildoonet/tf-pose-estimation#148]
Hey, I am trying to how to generate the groundtruth heatmap and find in you definition, there is a term 18: background. I am quite confused since all the rest of 18 heatmaps are generated from (x,y) of key points but what is background, how can i get it from COCO dataset?

**Comment by ildoonet** [comment]
@boldjoel background can be made by 

bg = 1.0 - sum(scores from points).

In coco dataset, it is not found.
