### ISSUE TITLE
Real-Time Application in Python

### ISSUE THREAD

**Issue by albertchristianto** [ildoonet/tf-pose-estimation#149]
Hi, 
Right now I re-implement this CMU human pose estimator in Keras. And i found out that the post-processing part is took a lot of time in python. I also have check your code for the post-processing part, but it's almost the same, I think. And your code can even run in CPU with decent FPS. 
Can you give me some tips how to boost the post-processing part in python? 
Thank you very much.

**Comment by ildoonet** [comment]
I implement the post processing part with NUMPY and I put efforts on it to run parallel. Also, some early rejection and python optimization were used. 

But, eventually, I'm going to implement this code again, It will be faster :)

**Comment by albertchristianto** [comment]
Wow, You have done a great job. 
Anyways, thank you for sharing some tips.
best regards,
albert
