### ISSUE TITLE
Floating head

### ISSUE THREAD

**Issue by lesreaper** [ildoonet/tf-pose-estimation#151]
I know this may sound a little strange, but does anyone know how I would segment the head in the image and just ignore the rest of the body?

That is, out of the whole image, the only thing you would see is a floating head.

**Comment by ildoonet** [comment]
This is much related to segmentation problem.

But if you want to do that with this code, you should implement some heuristics that crops images by using coordinates of nose, ears, ...

This is not related to the pose estimation, I'm closing this.
