### ISSUE TITLE
run_video.py missing definition

### ISSUE THREAD

**Issue by ss32** [ildoonet/tf-pose-estimation#157]
There is a missing definition in line 21 of `run_video.py`

```
- stringToBool(input_str):
+ def stringToBool(input_str):
```

**Comment by TTitcombe** [comment]
I've opened a pull request. (incredibly stupid mistake on my part)

**Comment by ildoonet** [comment]
@ss32 
@TTitcombe 

Right, I fixed the problem, but I didn't update it yet. 

 I will commit it within a day.
