### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pmuvva** [ildoonet/tf-pose-estimation#160]
I followed Installation setup in Mac machine:

git clone https://www.github.com/ildoonet/tf-openpose
cd tf-openpose
pip3 install -r requirements.txt.  after ran this command immediately I got below error:

Using cached https://files.pythonhosted.org/packages/4b/fb/2b954d2a38c9a0ef1da6a46737a75b4dbf6f60e5dad0f267a4ec5ece20de/AST-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zh/vh0sp5_90jzfbsw_jyjdsryr0000gn/T/pip-install-o3oe7987/ast/setup.py", line 6, in <module>
        README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/zh/vh0sp5_90jzfbsw_jyjdsryr0000gn/T/pip-install-o3oe7987/ast/AST/README'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zh/vh0sp5_90jzfbsw_jyjdsryr0000gn/T/pip-install-o3oe7987/ast/

Any help can be appreciated  to resolve this issue.

In my Mac I installed tensorflow 1.8.0 ,python3 and opencv3.

**Comment by jsgilberto** [comment]
Hi, I had the same error, and it turns out that python3 comes with AST. So you just have to install the other dependencies from the requirements.txt

**Comment by pmuvva** [comment]
Thank you. I installed other modules based on requirements.txt
