### ISSUE TITLE
Question about the Weights converted from Caffe format to tensorflow

### ISSUE THREAD

**Issue by mrc1992** [ildoonet/tf-pose-estimation#168]
@ildoonet  Thanks for your works about pose estimation!  Recently I have evaluated the CMU model which you have converted to tensorflow. But the AP is not good enough(4-scale) as we can see in the origin paper, here is my results:

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.453
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.676
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.469
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.392
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.563
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.485
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.697
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.498
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.392
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.631

So I want to confirm that whether the weights is 'pose_iter_440000.caffemodel' or not. Or, I write the wrong evalution code. 
Thanks!

**Comment by mrc1992** [comment]
@ildoonet  Hi, I realize you have upgrade a reproduce branch and I download the new cmu model, then I evaluate this model(4-scale) and get a good result, here is my results(the first 100 images in 2014val):
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.595
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.813
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.619
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.528
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.711
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.624
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.823
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.533
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.771

Thanks again for your great works!

**Comment by ildoonet** [comment]
Yeah, you need to 'REDOWNLOAD' weight files. 

Thanks for your sharing and commenting!

**Comment by lijing271** [comment]
@mrc1992 how can i get the reproduce branch?

**Comment by HONGJUNRL** [comment]
> @ildoonet Hi, I realize you have upgrade a reproduce branch and I download the new cmu model, then I evaluate this model(4-scale) and get a good result, here is my results(the first 100 images in 2014val):
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.595
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.813
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.619
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.528
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.711
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 20 ] = 0.624
> Average Recall (AR) @[ IoU=0.50 | area= all | maxDets= 20 ] = 0.823
> Average Recall (AR) @[ IoU=0.75 | area= all | maxDets= 20 ] = 0.648
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.533
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.771
> 
> Thanks again for your great works!

could you please tell me how to evaluate with multi scale?

**Comment by HONGJUNRL** [comment]
@FoolishMao could you tell me how to evaluate with multi scale?

**Comment by HONGJUNRL** [comment]
@FoolishMao Sorry to interrupt you, could you tell me how to evaluate with multi scale? I can not get the result you mentioned above
