### ISSUE TITLE
run.py with model graph cmu

### ISSUE THREAD

**Issue by techjun** [ildoonet/tf-pose-estimation#169]
Thanks for sharing neat code.

I have a problem with running cmu model, I downloaded pb file you wrote in download.sh with cmd and browser. But i get this error

### [[Node: TfPoseEstimator/conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](TfPoseEstimator/preprocess_subtract, TfPoseEstimator/conv1_1/weights)]]

when i run mobilenet_thin model it works well.. how can i solve this problem?

**Comment by ildoonet** [comment]
Upgrade your tensorflow.

**Comment by guohengkai** [comment]
@ildoonet Hi, I'm using Tensorflow 1.4.1 and have got the same error. Have I missed anything? Thanks.

**Comment by dlwogns0128** [comment]
@guohengkai upgrade tensroflow too.
