### ISSUE TITLE
reproducing mobilenet_thin results

### ISSUE THREAD

**Issue by mrT23** [ildoonet/tf-pose-estimation#170]
hello.

i am trying to reproduce the ap50 results of the mobilenet_thin model given in:
https://www.dropbox.com/s/09xivpuboecge56/mobilenet_0.75_0.50_model-388003.zip?dl=0
this model has an impressive ap50 0f 0.69

so far, when training mobilenet_thin i could only get ap50 of 0.56, which is similar to:
https://github.com/ildoonet/tf-pose-estimation/blob/reproduce/etcs/experiments.md

what is the difference between the ref model and the 'mobilenet_thin' model given in train.py ?

thanks,
tal

**Comment by ildoonet** [comment]
I'm not sure your question. 

How did you test the dropbox weights?

**Comment by ildoonet** [comment]
@mrc1992 First of all, that is not my code, and that code have some bugs. I already push evaluation code on 'reproduce' branch which will be merged today.

**Comment by ildoonet** [comment]
@mrc1992 @mrT23 okay, any further questions? or please close this issue.

**Comment by thancaocuong** [comment]
@mrT23 can you send me the trained model of mobilenet thin? I really appreciate that. Please send to my email (cuong@asilla.net). thank you

**Comment by mrT23** [comment]
@thancaocuong 
i am sorry, this work was done two years ago, i moved to other areas sense and i dont know where the model is

**Comment by thancaocuong** [comment]
@mrT23  thank you
