### ISSUE TITLE
￼Out of memory

### ISSUE THREAD

**Issue by TwT520Ly** [ildoonet/tf-pose-estimation#173]
When i trained the model used 'train.py', `_, gs_num = sess.run([train_op, global_step])` in line 205. Memory is 32G, but also out of memory.I think that using TensorPack to load data result in it.

**Comment by 1icas** [comment]
less batchsize  less quene size

**Comment by TwT520Ly** [comment]
Thanks. I try it  again.

**Comment by sanwong15** [comment]
I had to change it to batch_size = 16 to allow it to run with 2 GTX1080
