### ISSUE TITLE
enqueuer.last_dp out of bounds error

### ISSUE THREAD

**Issue by vincentwen1995** [ildoonet/tf-pose-estimation#174]
Hi. Recently when I was trying to train the network using train.py based on the pretrain cmu network,after 1000 global step when the validation and sample images are loaded, I came across with an out of bounds error on line 267 of train.py, writing that 
`sample_image = [enqueuer.last_dp[0][i] for i in range(4)]`
`IndexError: index 1 is out of bounds for axis 0 with size 1`
The parameters I was using are --batchsize=1, --max-epoch=1 and --lr=0.001.
My current guess is that maybe the batchsize is too small, since the other hyperparameters seems irrelevant to the issue, but I am not sure and it takes quite some time training, especially loading the validation images, before I can try it out, so I would appreciate if you have any experience with this error.

**Comment by vincentwen1995** [comment]
As I tried with a batch_size of 10 (recommended in training.md), I still got an error
"Cannot feed value of shape (0,) for Tensor 'fifo_queue_Dequeue:0', which has shape '(10, 368, 368, 3)'" pointing to tran.py at line 271 where the code is 
`feed_dict = {q_inp: np.array((sample_image + val_image) * (args.batchsize // 16))}`
So I suppose the batchsize of 10 divided by 16 would give a 0 that messes up the sample + validation image input. Yet I do have a question about the meaning of this "args.batchsize // 16", whay is it there and how can I tweek it to be more dynamic with different batch sizes?

**Comment by Naykira** [comment]
Hi @vincentwen1995 , I too am facing the same issue. Were you able to solve it?

**Comment by vincentwen1995** [comment]
@Naykira Hi, afterwards I bypassed the problem by using batch_size larger than 16 as can be seen in my comment above.

**Comment by Naykira** [comment]
@vincentwen1995 Thanks for the reply. Unfortunately, I get resource exhausted error when my batchsize = 16. Do you think changing the queue size would help in this case?

**Comment by vincentwen1995** [comment]
@Naykira Try changing the floor division in the line 
`outputMat = sess.run(
                    outputs,
                    feed_dict={q_inp: np.array((sample_image + val_image)*(args.batchsize // 16))}
                )` 
into something smaller like 1 or 2 and try with a smaller batch size. I am not too sure of why originally it is floor divided by 16 but seems quite casual to me.

**Comment by chrisskab** [comment]
@vincentwen1995 Did it solve your problem ?
