### ISSUE TITLE
Try to train with single specified gpu but it train with gpu:0 and gpu:1

### ISSUE THREAD

**Issue by AndrewSoul** [ildoonet/tf-pose-estimation#180]
Hi, thanks for your great work.  
When I tried to train the model with single  gpu(I choose --gpus=1),  it did train with gpu:0 and gpu:1. Probably  it's because the code "for gpu_id in range(arg.gpus): "?  But I want to train with gpu:0.  Could you please tell me what should I do?

**Comment by 1icas** [comment]
export CUDA_VISIBLE_DEVICES=0; python3 train.py

**Comment by AndrewSoul** [comment]
Ok, thanks for your reply~@1icas
