### ISSUE TITLE
Unable to build pafprocess on Mac OSX

### ISSUE THREAD

**Issue by khanhlvg** [ildoonet/tf-pose-estimation#181]
# Issue
* When I attempt to build pafprocess following this [instruction](https://github.com/ildoonet/tf-pose-estimation/tree/master/src/pafprocess), it failed
* Error message:
`pafprocess.cpp:15:5: error: 'round' is missing exception specification 'throw()'
int round(float v);
    ^
                   throw()
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:1437:46: note:
      previous declaration is here
inline _LIBCPP_INLINE_VISIBILITY float       round(float __lcpp_x) _NOEX...
                                             ^
pafprocess.cpp:235:5: error: 'round' is missing exception specification
      'throw()'
int round(float v) {
    ^
                   throw()
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:1437:46: note:
      previous declaration is here
inline _LIBCPP_INLINE_VISIBILITY float       round(float __lcpp_x) _NOEX...
                                             ^
2 errors generated.`

# Solution
* The round() function in [pafprocess.cpp](https://github.com/ildoonet/tf-pose-estimation/blob/master/src/pafprocess/pafprocess.cpp#L15) is incompatible with the one in math.h, which caused the error. Why did you redefine round()?
* I made it work by removing the round() function definition and implementation.

**Comment by ildoonet** [comment]
Thanks, I will remove round function. I didn't know the function is already exist in math.h.
