### ISSUE TITLE
issue on train and eval: mask.py error 

### ISSUE THREAD

**Issue by AndrewSoul** [ildoonet/tf-pose-estimation#182]
Hi. When I trained the model,  there was  a err:
    mask.py err= no module named pycocotools._mask
Someone can help me ?

**Comment by lyyiangang** [comment]
pip3 install cython. and then reinstall your cocoapi may fix this issue.

**Comment by sungwonida** [comment]
I have the same issue. I tried the command above and the error message is same.

**Comment by AndrewSoul** [comment]
Yes. Install cython and run :
$ cd cocoapi/PythonAPI
$ python3 setup.py build_ext --inplace
$ python3 setup.py build_ext install
That fixed the problem. My python version is 3.6.5. Without cython, maybe you can't get generated file "_mask.c".
