### ISSUE TITLE
run_video.py no skeleton being drawn

### ISSUE THREAD

**Issue by measke** [ildoonet/tf-pose-estimation#186]
Hi
The image and webcam demos are working fine. However the run_video.py returns only background video without any skeletons being drawn. As the video finishes playing I get the following error:

Exception: The image is not valid. Please check your image exists.

Full error log attached.
[error3.txt](https://github.com/ildoonet/tf-pose-estimation/files/2044552/error3.txt)

Any help would be appreciated.

**Comment by measke** [comment]
I managed to solve the issue myself by combining run_webcam.py and run_video.py. I must note that I do not have a programming background so I am not 100% sure why it works this way. It seems that resizing fixed the issue.

I run it with the following command (similar to webcam demo):

$ python run_video.py --model=mobilenet_thin --video=video.mp4 --resize=432x368


    import argparse
    import logging
    import time
    
    import cv2
    import numpy as np
    
    from estimator import TfPoseEstimator
    from networks import get_graph_path, model_wh
    
    logger = logging.getLogger('TfPoseEstimator-Video')
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter('[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s')
    ch.setFormatter(formatter)
    logger.addHandler(ch)
    
    fps_time = 0
    
    
    if __name__ == '__main__':
        parser = argparse.ArgumentParser(description='tf-pose-estimation Video')
        parser.add_argument('--video', type=str, default='')
        parser.add_argument('--resize', type=str, default='0x0',
                            help='if provided, resize images before they are processed. default=0x0, Recommends : 432x368 or 656x368 or 1312x736 ')
        parser.add_argument('--resize-out-ratio', type=float, default=4.0,
                            help='if provided, resize heatmaps before they are post-processed. default=1.0')
        parser.add_argument('--model', type=str, default='mobilenet_thin', help='cmu / mobilenet_thin')
        parser.add_argument('--show-process', type=bool, default=False,
                            help='for debug purpose, if enabled, speed for inference is dropped.')
        parser.add_argument('--showBG', type=bool, default=True, help='False to show skeleton only.')
        args = parser.parse_args()
    
        logger.debug('initialization %s : %s' % (args.model, get_graph_path(args.model)))
        
        w, h = model_wh(args.resize)
        if w > 0 and h > 0:
            e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
        else:
            e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368))
                
        cap = cv2.VideoCapture(args.video)
    
        if cap.isOpened() is False:
            print("Error opening video stream or file")
        while cap.isOpened():
            ret_val, image = cap.read()
            
            logger.debug('image process+')
            humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=args.resize_out_ratio)
            if not args.showBG:
                image = np.zeros(image.shape)
            
            logger.debug('postprocess+')
            image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False)
    
            logger.debug('show+')
            cv2.putText(image, "FPS: %f" % (1.0 / (time.time() - fps_time)), (10, 10),  cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
            cv2.imshow('tf-pose-estimation result', image)
            fps_time = time.time()
            if cv2.waitKey(1) == 27:
                break
    
        cv2.destroyAllWindows()
    logger.debug('finished+')

**Comment by juciny** [comment]
bingo

**Comment by Usernamezhx** [comment]
you are so coooooool

**Comment by sarahzhouUestc** [comment]
Thank you so much !!!

**Comment by DilaraSina** [comment]
Hi, thanks for your work, when I run this code, I got below error: 

>   from . import decays
  File "/home/anaconda3/lib/python3.6/site-packages/estimator/decays.py", line 7, in <module>
    cosine = tf.train.cosine_decay
AttributeError: module 'tensorflow.python.training.training' has no attribute 'cosine_decay'

Maybe, do you know how to solve it? Thanks in advance.

**Comment by xiaopingxiao** [comment]
> Hi, thanks for your work, when I run this code, I got below error:
> 
> > from . import decays
> > File "/home/anaconda3/lib/python3.6/site-packages/estimator/decays.py", line 7, in 
> > cosine = tf.train.cosine_decay
> > AttributeError: module 'tensorflow.python.training.training' has no attribute 'cosine_decay'
> 
> Maybe, do you know how to solve it? Thanks in advance.

Hello, I have encountered the same problem. Have you solved it

**Comment by at-Jm** [comment]
Thank you!!
