### ISSUE TITLE
Recognising human-like arms [Question]

### ISSUE THREAD

**Issue by Anitkrun** [ildoonet/tf-pose-estimation#188]
I was wondering how can one can train a model that can detect the poses/stances that a particular "humanoid" arm (like that of asimo) can attain?

I think it would be similar to what kind of training is done with human images. Or maybe retrain a model that already detects human arms?

**Comment by ildoonet** [comment]
I suggest that You need to gather images and annotations first. And then, finetune the model with the new data.

**Comment by Anitkrun** [comment]
Thank you for the response.

My next step was exactly that. I will let you know if it works as required.

**Comment by Anitkrun** [comment]
I'm really sorry to post this here, but can you point me as to how do i annotate the images for the estimation of poses? I mean certainly there is something( if not a lot ) in between, but my knowledge is limited.
