### ISSUE TITLE
Faster augmentation

### ISSUE THREAD

**Issue by anatolix** [ildoonet/tf-pose-estimation#19]
I've made very fast augmentation server/iterator for keras version of project

It augments approx 140 images per second(original caffe C++ code augments 30).
Trick is in making whole augmentation with one single warpAffine, and vectorized generation of heamaps without 2 nested loops for coordinates.

https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation
If you like it I could make pull request here

**Comment by ildoonet** [comment]
@anatolix That is amazing. Pull Request is always welcome.

I will wait for your awesome codes!

**Comment by pkdogcom** [comment]
@anatolix Any plan to make pull request recently? It would be nice if data augmentation can be speed up as training is pretty slow right now.

**Comment by ildoonet** [comment]
Close due to inacitivity.
