### ISSUE TITLE
Why the old version is more accurate?

### ISSUE THREAD

**Issue by techjun** [ildoonet/tf-pose-estimation#192]
I tested with default arguments in pafprocess new version but the outputs are less accurate than the old version

![image](https://user-images.githubusercontent.com/34329960/40658008-be61b594-6384-11e8-9280-775f58d93698.png)

![image](https://user-images.githubusercontent.com/34329960/40658030-d439f9f8-6384-11e8-8115-ef4b11f9f464.png)

both are same cmu model and graph_opt

**Comment by toshiy104** [comment]
in pafprcess.h, the number of the inner product of the vector between body parts and the paf exceeds the threshold is set to 9 times (THRESH_VECTOR_CNT1), but it is set to 8 times in the original openpose.
For this reason, extraction of pair candidates may be decreasing.

**Comment by toshiy104** [comment]
modify pafprcess.h as follows and results are as follows.
//const float THRESH_HEAT = 0.05;
const float THRESH_HEAT = 0.1;
const float THRESH_VECTOR_SCORE = 0.05;
//const int THRESH_VECTOR_CNT1 = 9;
const int THRESH_VECTOR_CNT1 = 8;

![apink1](https://user-images.githubusercontent.com/1628377/40780156-679aaa10-6512-11e8-9cf6-cd673dda2681.png)

The remaining cause may be that the process of finding tensor_peaks at 160 lines of estimator.py is different from the original openpose.

**Comment by siddharthrajpatel** [comment]
Hi @techjun @toshiy104 , how can i use and download the older version of the codes?

**Comment by ildoonet** [comment]
@techjun Image resolution can be the reason. The input image you used have a long height relative to its width. So, If you change the resolution of the input for the network as similar as the image's aspect ratio, this will be resolved.

**Comment by techjun** [comment]
Thanks for all comments maybe I should read more about paper and codes.
@siddharthrajpatel  I downloaded before updates.
