### ISSUE TITLE
Resolution error

### ISSUE THREAD

**Issue by siddharthrajpatel** [ildoonet/tf-pose-estimation#204]
Hi, while giving the realtime webcam command :

"python src/run_webcam.py --model=mobilenet_thin --resolution=432x368 --camera=0"

i am getting the following resolution error:

![resol](https://user-images.githubusercontent.com/36742332/40897154-f5f906fa-67d6-11e8-89a2-6a5266972dd2.JPG)

How can i solve this?

**Comment by ildoonet** [comment]
change resolution to resize

See the above guide.

**Comment by siddharthrajpatel** [comment]
Hey, @ildoonet  thanks , now it works :)
