### ISSUE TITLE
The run_video.py my be wrong in Ubuntu16.04

### ISSUE THREAD

**Issue by juciny** [ildoonet/tf-pose-estimation#207]
when I run run_video.py, Bone spots are not detected
so I compare run_video.py with run.py
humans = e.inference(image,resize_to_default=(w > 0 and h > 0), upsample_size=args.resize_out_ratio)
that is right
maybe my environment configuration is wrong

**Comment by JakubWojciechowski** [comment]
Hey,
for me, run_video.py did not work properly with the default upsample_size. after changing this parameter to the one in the run.py:
humans = e.inference (image, upsample_size = 4.0)
everything works correctly.
Good luck!

**Comment by Aditya-11** [comment]
Thank you very much @JakubWojciechowski

**Comment by dlwogns0128** [comment]
Thank you so much @JakubWojciechowski :0
