### ISSUE TITLE
Annotations for training

### ISSUE THREAD

**Issue by arnitkun** [ildoonet/tf-pose-estimation#214]
This might be a stupid question but I have no idea in which format do I annotate images for retraining; JSON or something else, or is any format fine? 

The annotations in question refer to annotation of images of arms( kind of).

EDIT: actually I would like to know the tools if there are any, that allow me to annotate segmentations and keypoints.

**Comment by Oigile** [comment]
I would also like to know what is the best way to annotate images for retraining. 
So far I have found that it might be best to convert the annotations to COCO Format (json format), but I am not sure if it is necessary. Also I guess there may be some tools available to convert annotations in COCO format, which you might be able to use. 
Correct me if I am wrong, I am just getting started in this field.

**Comment by tomercohen11** [comment]
Did anyone solve this?

**Comment by arnitkun** [comment]
I really apologize for the (super) late reply. Busy.

The ideal course of action is to go the json way since most annotation are json and one should face less compatibility issues as such. Yes @Oigile  you can use the coco-toolbox for this, It contains the necessary APIs for this. You can also check how the images were annotated using the toolbox.

As for the annotation tool, I would suggest using a polygon tool and modify it should there be no point tool.
