### ISSUE TITLE
Saved Model for Google Cloud ML

### ISSUE THREAD

**Issue by Cangrc** [ildoonet/tf-pose-estimation#22]
Hello @ildoonet,

I would like to deploy your project to Google Cloud ML but checkpoint files are not enough for deploying and then getting predictions. I have tried some solutions available on following links but I couldn't manage to do it: 

Link1: https://stackoverflow.com/questions/42932714/deploy-a-model-on-ml-engine-exporting-with-tf-train-saver

Link2: https://cloud.google.com/ml-engine/docs/deploying-models

Can you please provide necessary files on your Github repository?

Kind Regards
Can Giracoglu

**Comment by ildoonet** [comment]
I have a plan to provide 'pb' graph file which is exported freezed graph for tensorflow.

It will take some time, And you need to write codes to process the output from the network.

**Comment by ildoonet** [comment]
@Cangrc I uploaded pb files and scripts than handles.
