### ISSUE TITLE
Running the command "swig -python -c++ pafprocess.i && python setup.py build_ext --inplace" is giving multiple compilation errors

### ISSUE THREAD

**Issue by tianjiahao** [ildoonet/tf-pose-estimation#226]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
I Just replace every and and or in the code by && and ||, respectively.
 But still the same error：error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2;
Please help in resolving this error.
Thanks

**Comment by lyyiangang** [comment]
Do you install swig in your machine? I think that should be more detail info. you could paste all of them here.

**Comment by ashish10alex** [comment]
I am getting this error on running the swig command. I have installed swig, cython etc.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by tianjiahao** [comment]
C:\Users\Administrator>cd C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\pafprocess

C:\Users\Administrator\Desktop\tf-pose-estimation-master\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
D:\swigwin-3.0.12\swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include -I. -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppafprocess.cpp /Fobuild\temp.win-amd64-3.5\Release\pafprocess.obj
pafprocess.cpp
c:\users\administrator\desktop\tf-pose-estimation-master\tf_pose\pafprocess\pafprocess.h(6): warning C4305: “初始化”: 从“double”到“float”截断
c:\users\administrator\desktop\tf-pose-estimation-master\tf_pose\pafprocess\pafprocess.h(7): warning C4305: “初始化”: 从“double”到“float”截断
c:\users\administrator\desktop\tf-pose-estimation-master\tf_pose\pafprocess\pafprocess.h(10): warning C4305: “初始化”: 从“double”到“float”截断
pafprocess.cpp(15): error C2556: “int round(float)”: 重载函数与“float round(float) noexcept”只是在返回类型上不同
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(278): note: 参见“round”的声明
pafprocess.cpp(15): error C2371: “round”: 重定义；不同的基类型
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(278): note: 参见“round”的声明
pafprocess.cpp(64): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(65): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(83): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
pafprocess.cpp(147): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(167): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(174): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(175): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
pafprocess.cpp(186): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
pafprocess.cpp(195): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
pafprocess.cpp(199): warning C4244: “return”: 从“float”转换到“int”，可能丢失数据
pafprocess.cpp(223): error C2264: “round”: 函数定义或声明中有错误；未调用函数
pafprocess.cpp(224): error C2264: “round”: 函数定义或声明中有错误；未调用函数
pafprocess.cpp(235): error C2556: “int round(float)”: 重载函数与“float round(float) noexcept”只是在返回类型上不同
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(278): note: 参见“round”的声明
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2

**Comment by tianjiahao** [comment]
I find the location of rc.exe. Its path is C:\Program Files (x86)\Windows Kits\8.1\bin\x64
Make the  path included by PATH environment variable ,but still have the same error.

**Comment by siddharthrajpatel** [comment]
Hi @tianjiahao bro! I've someway managed this error by replacing all "or" with "||"  and all "and" with "&&". Also it need to change the round function name (i've named it as "rounds") beacuse it collides with cmath round function. Now you have just to run "swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
" and it will compile. Then should work everything (hope it!)

**Comment by siddharthrajpatel** [comment]
make sure you have cython and visual c++ build tools installed also

**Comment by tianjiahao** [comment]
@siddharthrajpatel 
According to your suggestion, this order"swig -python -c++ pafprocess.i && python setup.py build_ext --inplace
" has been successful. Thank you very much!
