### ISSUE TITLE
unable to find file 'pafprocess.i'

### ISSUE THREAD

**Issue by wkdwnsqja** [ildoonet/tf-pose-estimation#227]
It still in folder... what should i do?

**Comment by lyyiangang** [comment]
Any more error logs?

**Comment by wkdwnsqja** [comment]
(py16) C:\Windows\System32\tf-openpose\tf_pose\pafprocess>swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace
Unable to find file 'pafprocess.i'.
Unfortunately,i can't see anymore log..

**Comment by lyyiangang** [comment]
do you install cython? you can try:
pip3 install cython，and then use your command again.

**Comment by wkdwnsqja** [comment]
I have cython..

**Comment by wkdwnsqja** [comment]
(jun) C:\Windows\System32\tf-openpose>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    subprocess.check_output(["bash", "models/graph/cmu/download.sh"], cwd=cwd)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]
I running setup.py

**Comment by wkdwnsqja** [comment]
I solve it! swig doesn't recognize file that is generated paths are too long

**Comment by tianjiahao** [comment]
@wkdwnsqja the same error with you:FileNotFoundError: [WinError 2]
swig doesn't recognize file that is generated paths too long , how to solve it?

**Comment by ndesamuelmbah** [comment]
@wkdwnsqja could you explain how you solved it?

**Comment by wkdwnsqja** [comment]
It happened a long time ago and I'm not sure my memory. I think I changed the file from long path to short path such as C drive.

**Comment by tyler-po** [comment]
@ndesamuelmbah cd into the 'tf_pose/pafprocess' folder and run the command in there

**Comment by tealeeseng** [comment]
how to have bash under windows?

Traceback (most recent call last):
File "setup.py", line 15, in
subprocess.check_output(["bash", "models/graph/cmu/download.sh"], cwd=cwd)
File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
**kwargs).stdout
