### ISSUE TITLE
Error while installing swig

### ISSUE THREAD

**Issue by VivianDabre** [ildoonet/tf-pose-estimation#236]
I am trying installing swig but getting the same error.
![image](https://user-images.githubusercontent.com/20701330/41912055-cdf60a32-7991-11e8-8dc4-4323ff2b8999.png)

**Comment by wkdwnsqja** [comment]
It is Not registered in pypl. follow this link: 

> http://www.swig.org/

 or If you use anaconda, 
use  `conda install -c anaconda swig `
