### ISSUE TITLE
speed is lower and lower when running continuously!

### ISSUE THREAD

**Issue by hian90** [ildoonet/tf-pose-estimation#240]
I used mobilenet_thin model, and i got about ~200 ms for inference one image
(set 368,368 input, and default others)

when i put this on Flask and Running.. 
( using gunicorn, run 2~4 worker)
( model init one time, and inference picture continuously..)

is run well, but i try to put load to pose-estimation, by using jmeter

inference time getting more and more slower! it can be seen few hours later(4hours - about 10% slower) 

even if free cpu, and memory are enough.

I can't find this problem cause by if your code or tensorflow's architecture.. 

could you give me some advice? 

Thank u :)

**Comment by ildoonet** [comment]
Have no idea. I guess that your web server have some problems.

**Comment by YuhaoYeSteve** [comment]
Have you solve this problem, I have the same problem as what you described, thank you!

**Comment by djstrong** [comment]
If this (https://stackoverflow.com/a/49471633/10026323) is applicable then the model should be slower from the fist request. Are you using CPU or GPU for tf?
