### ISSUE TITLE
how to visualize heatmap and pafmap?

### ISSUE THREAD

**Issue by nvnnghia** [ildoonet/tf-pose-estimation#247]
I want to visualize heatmap and pafmap like this [image](https://github.com/ildoonet/tf-pose-estimation/blob/master/etcs/inference_result2.png). Please help.

**Comment by nvnnghia** [comment]
@despild Thanks for the suggestion, I've just tried but didn't work

**Comment by despild** [comment]
In my case, I can get this image
![figure_1](https://user-images.githubusercontent.com/1145252/42150489-057e6f44-7e15-11e8-84a8-b9906357121b.png)

**Comment by nvnnghia** [comment]
Here is what I got. ![image](https://user-images.githubusercontent.com/31887969/42151163-08bd48ae-7e17-11e8-9129-af8490a02493.png)

**Comment by despild** [comment]
I think your system didn't recognize person correctly.
How about try sample image that is provided by repository(./images/p1.jpg)

**Comment by nvnnghia** [comment]
Thank you very much. I got what I wanted. ![image](https://user-images.githubusercontent.com/31887969/42151765-f20b0b9e-7e18-11e8-84d0-d596f5991a7d.png)

**Comment by despild** [comment]
Cool congratulation!! :)
