### ISSUE TITLE
Joints Coordinates

### ISSUE THREAD

**Issue by oguzhankarabulut** [ildoonet/tf-pose-estimation#25]
Thanks for project, it is amazing!!!

I want to ask, how can i reach to joints coordinates?

Regards

**Comment by izaakvc** [comment]
In inference.py there is a line:
 `humans = estimate_pose(heatMat, pafMat)`
You can find joint number `M` of person `N` in `humans[N][1][M]`

For a example, look at the `draw_humans` junction in common.py. There the joints are drawn one by one.

**Comment by oguzhankarabulut** [comment]
Thank you so much!

**Comment by ildoonet** [comment]
I'm currently trying to refactor codes to use this much easier. 

Thanks.

**Comment by oguzhankarabulut** [comment]
Hi again @ildoonet 

Is there any news about to use this much easier? 
Regards
