### ISSUE TITLE
the loss in the code is not the same as the loss in the paper？

### ISSUE THREAD

**Issue by lijing271** [ildoonet/tf-pose-estimation#253]
Is it missing the w(p) factor？which will result in a great loss during training.

**Comment by lijing271** [comment]
i get it! thanks your works very much!

**Comment by ahhan02** [comment]
@lijing271  I can not find where the w(p) factor is... would you point out where it is? thx

**Comment by chrisskab** [comment]
@lijing271 @ahhan02 What is the title of the paper you are referring to ? Thank you !

**Comment by ahhan02** [comment]
@chrisskab Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields
