### ISSUE TITLE
Is there a standard way to get the original heatmaps?

### ISSUE THREAD

**Issue by gitpharm01** [ildoonet/tf-pose-estimation#257]
Hi, I want to studying the original heat maps(Not the peak points shown by run.py) 
I know the original version written in c++ have a tutorial that will do this:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.cpp
But I want to focus on your version, since you boosted it up SOOO much with mobilenet backbone.

Is there any way I can get the original heat maps and save them?
I'm currently studying estimator.py and trying to get the heat maps. 
Do you have any suggestions or warnings?
Thanks!

**Comment by lyyiangang** [comment]
use gettensorbyname to get heatmap tensor

**Comment by gitpharm01** [comment]
Wow! I never thought that would be so simple. Thank you a lot!
I was trapped at this place for a long time.

**Comment by December-boy** [comment]
Hi, @lyyiangang @gitpharm01  could you provide more details about how to use gettensorbyname  to get the heat maps? The output of the cmu model include 57 feature maps and the  first 19 are key joints, the rests are heat maps? can I get them by the index of them?
