### ISSUE TITLE
Missing loss_last() for personlab_resnet101 model

### ISSUE THREAD

**Issue by Naykira** [ildoonet/tf-pose-estimation#285]
Hello @ildoonet, thanks a lot for the tf implementation of openpose. I have a question regarding the loss_last() function used to obtain heat and vectormaps in train.py. 

Is this a user defined function for the mobilenet models or is it built-in? 
If user defined, how does one go about doing it? 
If built-in, does it not exist for personlab_resnet101 model? 
I would be grateful for any suggestions regarding this. Thanks!

**Comment by Naykira** [comment]
Figured it out. Thanks anyway!

**Comment by Naykira** [comment]
Hi! Check out line 97 [here](https://github.com/ildoonet/tf-pose-estimation/blob/master/tf_pose/network_mobilenet.py). You need to write a similar function for PersonLab  network as well.

**Comment by meetdave06** [comment]
@Naykira  Could you please share the function? Or make a pull request?

**Comment by Naykira** [comment]
Sorry! I ended up using Mobilenet itself and so didn't need to create such a function for PersonLab.
