### ISSUE TITLE
where is the groundtruth part affinity vector field?

### ISSUE THREAD

**Issue by nvnnghia** [ildoonet/tf-pose-estimation#289]
Hi, Thanks for excellent works. 
In the training mode, we need the groundtruth part confidence map and the groundtruth part affinity vector field to calculate loss and update the model. But in the coco joint points dataset, we only have the groundtruth part confidence map. My question is where  is the groundtruth part affinity vector field? Thank you

Update: using joint points to create part affinity vector field 
![image](https://user-images.githubusercontent.com/31887969/43878888-6768baf4-9bdc-11e8-9bdb-6c61a1b87433.png)

**Comment by robertorovella91** [comment]
Hi to all, 
I have the same problem to understand how part affinity groundtruth vectors are computed in practice. In particular how to establish if a point p belong to a part of the limb or not. There is some segmentation before ? Thanks in advance
