### ISSUE TITLE
What is the meaning of 'upsample_size'

### ISSUE THREAD

**Issue by GreatGBL** [ildoonet/tf-pose-estimation#293]
in the code ' humans = e.inference(image, upsample_size=4.0)'
I test the number '4.0' affect the accuracy of skeleton node, but what is the relationship of it?

**Comment by shreyasrajesh** [comment]
It determines the size of the heatmap during the postprocessing. The higher the size of the heatmap during postprocessing the more accurate the results. However, the postprocessing speed reduces simultaneously.

**Comment by GreatGBL** [comment]
@shreyasrajesh 
Thanks for your help, and may I ask are there has a recommended value of it? I saw the default setting is 4.0, it is a suitable value? Thanks

**Comment by shreyasrajesh** [comment]
There's no such thing as a recommended value, its entirely based on your priority over speed or accuracy. I would say the default 4.0 is a good trade off and gives a combination of speed and accuracy.

**Comment by GreatGBL** [comment]
Well, I try the default setting, thanks for your answer
Best regards
