### ISSUE TITLE
Why some layers of Mobilenet are not used?

### ISSUE THREAD

**Issue by mandal4** [ildoonet/tf-pose-estimation#296]
Thanks for your great work:)
I have a question, why do the last 5 conv layers not used in you work?
Isn't it not used layers for training and inference, right?

        with tf.variable_scope(None, 'MobilenetV1'):
            (self.feed('image')
             .convb(3, 3, depth(32), 2, name='Conv2d_0')
             .separable_conv(3, 3, depth(64), 1, name='Conv2d_1')
             .separable_conv(3, 3, depth(128), 2, name='Conv2d_2')
             .separable_conv(3, 3, depth(128), 1, name='Conv2d_3')
             .separable_conv(3, 3, depth(256), 2, name='Conv2d_4')
             .separable_conv(3, 3, depth(256), 1, name='Conv2d_5')
             .separable_conv(3, 3, depth(512), 1, name='Conv2d_6')
             .separable_conv(3, 3, depth(512), 1, name='Conv2d_7')
             .separable_conv(3, 3, depth(512), 1, name='Conv2d_8')
             # .separable_conv(3, 3, depth(512), 1, name='Conv2d_9')
             # .separable_conv(3, 3, depth(512), 1, name='Conv2d_10')
             # .separable_conv(3, 3, depth(512), 1, name='Conv2d_11')
             # .separable_conv(3, 3, depth(1024), 2, name='Conv2d_12')
             # .separable_conv(3, 3, depth(1024), 1, name='Conv2d_13')
             )

**Comment by ildoonet** [comment]
After some trials, they are not that important for improving accuracy, so I removed them to reduce the inference time.

**Comment by chrisskab** [comment]
@ildoonet What is the mAP of the mobilenet architecture ?
