### ISSUE TITLE
Problematic when only upper part is visible 

### ISSUE THREAD

**Issue by Cangrc** [ildoonet/tf-pose-estimation#30]
Hello @ildoonet,

When for example people are sitting in front of their webcams, most of the time it cannot detect anything. Do we need to have full body for accurate results?

Kind Regards,

**Comment by ildoonet** [comment]
@Cangrc Right. I'm currently retraining the model with more robust codes.
Please wait couple of weeks so that I can publish new model and new codes.
Thanks.

**Comment by seovchinnikov** [comment]
hey @ildoonet!
Was the new model released?
Thank you

**Comment by ildoonet** [comment]
This will be resolved in reproduce branch. Closed.
