### ISSUE TITLE
Body part names

### ISSUE THREAD

**Issue by mbaytas** [ildoonet/tf-pose-estimation#301]
The body parts (i.e. keypoints) returned by `TfPoseEstimator.inference()` have integer indexes but no names.

I have compared the results I got from tf_pose to the [keypoint ordering given in the OpenPose documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#keypoint-ordering) for the 25-part COCO + foot model, and they do not seem to align.

How do we find out the names of the body parts that are being returned?

**Comment by GreatGBL** [comment]
class CocoPart(Enum):
    Nose = 0
    Neck = 1
    RShoulder = 2
    RElbow = 3
    RWrist = 4
    LShoulder = 5
    LElbow = 6
    LWrist = 7
    RHip = 8
    RKnee = 9
    RAnkle = 10
    LHip = 11
    LKnee = 12
    LAnkle = 13
    REye = 14
    LEye = 15
    REar = 16
    LEar = 17
    Background = 18

**Comment by mbaytas** [comment]
@GreatGBL thank you very much. Closing the issue.

I'll add that this information is to be found in the file [common.py](https://github.com/ildoonet/tf-pose-estimation/blob/460dfab9a73784455c314c7a979dd87a36b35f4f/tf_pose/common.py).

**Comment by askari12** [comment]
Hi , I was still having trouble in understanding which node is which body part. Can you direct me where it is mentioned in the code ?

**Comment by finnickniu** [comment]
@askari12  check the file of common.py
