### ISSUE TITLE
COCOPAIRS_NET

### ISSUE THREAD

**Issue by Naykira** [ildoonet/tf-pose-estimation#304]
Hello, thank you for tf implementation of Openpose. I have a question about the relationship between COCOPAIRS and COCOPAIRS_NET used in the inference part of the code. COCOPAIRS  is easy enough to understand but what's the logic behind the pairs of numbers in the COCOPAIRS_NET? Has anyone figured it out? Any help/suggestions would be greatly appreciated. Thanks!

**Comment by Naykira** [comment]
Just mentioning it in case someone else is also looking for an answer to the above question. The COCOPAIRS_NET contains the two PAF maps (among 38) for the corresponding limb mentioned in COCOPAIRS. The particular order in COCOPAIRS_NET is influenced by the order of body joints mentioned in __coco_vecs in pose_datset.py. So, if one needs to change the order or add/delete more body joints, all three need to be modified.

**Comment by Deicide-LC** [comment]
@Naykira  Excuse me, I also have the same problem, Have you figure it out?
