### ISSUE TITLE
Links to dropbox checkpoints no longer work

### ISSUE THREAD

**Issue by dcdolson** [ildoonet/tf-pose-estimation#328]
Have the saved checkpoints been moved?
I'm using the links from the README.

**Comment by Demonmikalis** [comment]
Yes I face the same problem, and I have sent the email to the authors for help

**Comment by KocsisV** [comment]
Any update?

**Comment by Demonmikalis** [comment]
No response... :(

**Comment by KocsisV** [comment]
Just noticed, that you can run the download.sh given model's folder (models/graph/cmu and models/graph/mobilenet_thin) that gets the weights file.
For the CMU model you can also convert it from the original caffe model weights.

**Comment by dcdolson** [comment]
I had to do this patch to get the download.sh to work:
https://github.com/dcdolson/tf-pose-estimation/commit/d1eb446c8049e954ccf415f0d1059ee57b90dcf5
However, I still wasn't able to use these checkpoints, which seem to come from a non-standard version of tensorflow.

**Comment by Demonmikalis** [comment]
> I had to do this patch to get the download.sh to work:
> [dcdolson@d1eb446](https://github.com/dcdolson/tf-pose-estimation/commit/d1eb446c8049e954ccf415f0d1059ee57b90dcf5)
> However, I still wasn't able to use these checkpoints, which seem to come from a non-standard version of tensorflow.

I downloaded the checkpoint named mobilenet_0.75_0.50_model-388003, but get the wrong results, it seems this checkpoint is only a pre-trained one but not converge. :(

**Comment by ildoonet** [comment]
Dropbox links are outdated and it is very hard for me to find suitable upload website and upload everytime. Please use graph files.
