### ISSUE TITLE
 Maybe a flip augmentation bug

### ISSUE THREAD

**Issue by tpys** [ildoonet/tf-pose-estimation#33]
I modify your code to do face alignment, after some training, I found some face images have wrong landmark localization, the landmark's order is wrong, when your draw line between part, they cross each other. so I think the 50% flip augmentation operation is not right.

you flip image with cv2.flip, flip landmark label with (w - x, y),  so the landmark order is changing.  In order to keep image and landmark correspondence, need change the landmark order to.  so I modify the code below:
```python
def pose_flip(meta):
    pairs = {0: 16, 1: 15, 2: 14, 3: 13, 4: 12, 5: 11, 6: 10, 7: 9, 8: 8, 9: 7, 10: 6,
             11: 5, 12: 4, 13: 3, 14: 2, 15: 1, 16: 0, 17: 26, 18: 25, 19: 24, 20: 23,
             21: 22, 22: 21, 23: 20, 24: 19, 25: 18, 26: 17, 27: 27, 28: 28, 29: 29, 30: 30,
             31: 35, 32: 34, 33: 33, 34: 32, 35: 31, 36: 45, 37: 44, 38: 43, 39: 42, 40: 47,
             41: 46, 42: 39, 43: 38, 44: 37, 45: 36, 46: 41, 47: 40, 48: 54, 49: 53, 50: 52,
             51: 51, 52: 50, 53: 49, 54: 48, 55: 59, 56: 58, 57: 57, 58: 56, 59: 55, 60: 64,
             61: 63, 62: 62, 63: 61, 64: 60, 65: 67, 66: 66, 67: 65}

    r = random.uniform(0, 1.0)
    if r > 0.5:
        return meta

    img = meta.img
    img = cv2.flip(img, 1)

    num = len(meta.joint_list)
    adjust_joint_list = [0] * num
    for index, joint in enumerate(meta.joint_list):
        if joint[0] < -100 or joint[1] < -100:
            adjust_joint_list[pairs[index]] = (-1000, -1000)
        else:
            adjust_joint_list[pairs[index]] = (meta.width - joint[0], joint[1])

    meta.joint_list = adjust_joint_list
    meta.img = img
    return meta
```
this is code is for face alignment, you need to change the pairs to human pose.

**Comment by ildoonet** [comment]
@tpys You are so right. I will correct the code and retrain the model accordingly.
Many Thanks.

**Comment by ildoonet** [comment]
@tpys Actually, It wasn't a bug. 

I already changed order of joints so that they will be adjusted in proper joint index.

See : https://github.com/ildoonet/tf-pose-estimation/blob/master/pose_augment.py#L174

**Comment by tpys** [comment]
@ildoonet Right, I remove these lines during modification and I forget that, embarrassing.  The code is totally fine.

**Comment by ildoonet** [comment]
@tpys No problem. Thanks for the comments.
