### ISSUE TITLE
pafprocess

### ISSUE THREAD

**Issue by shahzadmoghimifar** [ildoonet/tf-pose-estimation#333]
hello everybody
i use swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace but there is error.
is there any replace command?

**Comment by shahzadmoghimifar** [comment]
> hello everybody
> i use swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace but there is error.
> is there any replace command?

I solve it but I dont know video command running

**Comment by shahzadmoghimifar** [comment]
> > hello everybody
> > i use swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace but there is error.
> > is there any replace command?
> 
> I solve it but I dont know video command running

I use "python run_video.py --video=/hddext/shahzad/mel.mp4 --resolution=432x368 --model=mobilenet_thin --cvShowImage=showBG" command for run on video but I receive error as you can see :"usage: run_video.py [-h] [--video VIDEO] [--resolution RESOLUTION]
                    [--model MODEL] [--show-process SHOW_PROCESS]
                    [--showBG SHOWBG]
run_video.py: error: unrecognized arguments: --cvShowImage=showBG" 
How do I solve it?

**Comment by rag9704** [comment]
@shahzadmoghimifar  how did you solved it?

**Comment by shahzadmoghimifar** [comment]
> @shahzadmoghimifar how did you solved it?

conda install -c anaconda swig
pip3 install cython
after downloading program files you should use these commands step by step:
cd tf-pose-estimation-master/
cd tf_pose/
cd pafprocess/
swig -python -c++ pafprocess -i && python setup.py build_ext --inplace
