### ISSUE TITLE
Equivalent Openpose output

### ISSUE THREAD

**Issue by sophia-wright-blue** [ildoonet/tf-pose-estimation#334]
Hello,
 
 I'm looking to use the tf-pose-estimation repo to get the same output as what you obtain from the caffe Openpose repo when you run:

```
./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/result.avi --write_json output/
```

after running the above on the caffe Openpose, you get image frames on result.avi and the output JSON files in the folder output/

How do I get the same output from the tf-pose-estimation repo - what would be the command that I would need to run? 

Thank you,

**Comment by Sindreedelange** [comment]
@sophia-wright-blue Did you ever figure this out?

**Comment by sophia-wright-blue** [comment]
Hi @Sindreedelange , unfortunately, i have moved on to other projects, so I did not get a chance to work on this, hope you have better luck!
