### ISSUE TITLE
error: Setup script exited with  Matplotlib 3.0+ does not support

### ISSUE THREAD

**Issue by SungjungC** [ildoonet/tf-pose-estimation#337]
after I put  python setup.py install on terminal

it says like this.

error: Setup script exited with 
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.

This may be due to an out of date pip.

Make sure you have pip >= 9.0.1.

I don't know how to fix it :( 
I have pip 18.0 and Python 3.7.0.

Anybody help can me?

**Comment by roya90** [comment]
I faced the same issue

**Comment by SungjungC** [comment]
I solved this problem changing Python to Python 3 but I had another problem :(
