### ISSUE TITLE
No use of GPU for realtime webcam why?

### ISSUE THREAD

**Issue by jtruc** [ildoonet/tf-pose-estimation#339]
Hi,

I tried realtime webcam using this command : 
`$ python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0`

I checked my CPU and GPU usage : CPU 100% and GPU 0%

Would not it be more efficient with the use of GPU?

PC : i7-4810 CPU with nvidia Quadro K2100M

Regards

**Comment by rawandeheliah** [comment]
what did you do ? to run GPU with it?
