### ISSUE TITLE
What is the training settings of 'mobilenet_thin' graph.pb?

### ISSUE THREAD

**Issue by petertse612** [ildoonet/tf-pose-estimation#345]
@ildoonet 
Could you share the training settings of the mobilenet_thin/graph_opt.pb in the repository?

I found the settings below from training.md. Are you using these settings?

> model : vgg
> lr : 0.0001 or 0.00004
> input-width = input-height = 368x368 or 432x368
> batchsize : 10 (I trained with batchsizes up to 128, they are trained well)

**Comment by ildoonet** [comment]
#411 I shared parameters and changed default parameters accordingly.
