### ISSUE TITLE
qasciikey.cpp error !

### ISSUE THREAD

**Issue by rawandeheliah** [ildoonet/tf-pose-estimation#348]
i was running command : 
python3 run_video.py  --video=vid1.mp4

and it used to work , but without changing anything suddenly this error appeared and now it appears  every time I run the command 
error :
ASSERT: "false" in file qasciikey.cpp, line 501
Aborted (core dumped)

any solutions ?

**Comment by Unlingius** [comment]
have you solved your problem?

**Comment by rawandeheliah** [comment]
yes it appeared that is something with my laptop hardware :\

**Comment by Hackavist** [comment]
what was the problem ?
