### ISSUE TITLE
the version of CPU

### ISSUE THREAD

**Issue by andyqian2015** [ildoonet/tf-pose-estimation#35]
@ildoonet  Thx for your appreciation work. I say that you have implement the CPU version. how can I run on the CPU? when I run the command you give on the readme.all is running on the GPU. appreciation for your replying.

**Comment by ildoonet** [comment]
Could you please try like below commands? 

```
CUDA_VISIBLE_DEVICES="" python3 ...
```

If you have a tensorflow build for gpu, it try to use gpu as its default. 

So If you disable all cuda devices(gpus) as above command, tensorflow will automatically use cpu since it can not find any.

**Comment by andyqian2015** [comment]
thx for your reply.just right now  I change the version of tensorflow to CPU version and it works.thx

**Comment by andyqian2015** [comment]
@ildoonet  thx for your reply.just right now I change the version of tensorflow to CPU version and it works.thx
