### ISSUE TITLE
'No module named 'slidingwindow' 

### ISSUE THREAD

**Issue by gen21kawa** [ildoonet/tf-pose-estimation#351]
When I ran the following command, I encountered with the error I mentioned at the title. 
python3 run.py --model=mobilenet_thin --resize=432x368 --image=./images/p1.jpg

I fixed the error by changing tf_pose/estimator.py. 

import slidingwindow as sw
=>
import sys
sys.path.append('/slidingwindow')
import SlidingWIndow as sw

Hope it helps someone who has the same error.

**Comment by solitarysandman** [comment]
I resolved this issue by following the install instructions. 

```
$ git clone https://www.github.com/ildoonet/tf-openpose
$ cd tf-openpose
$ python setup.py install
```

**Comment by HARIHARAN1103** [comment]
check this one, for me it sloved
pip install slidingwindow

**Comment by ildoonet** [comment]
it was omited  in requirements. Now it is fixed. Thanks.

**Comment by tarokiritani** [comment]
@ildoonet I am still a bit confused. `slidingwindow` has been manually copied to `tf_pose/slidingwindow`, and maybe has been modified. Which version of `slidingwindow` should I use? The one in this repo or the original one which can be installed with pip?

**Comment by Marshajennifer** [comment]
import slidingwindow as sw
ModuleNotFoundError: No module named 'slidingwindow'

Tried pip install slidingwindow.
But again showing same error.
