### ISSUE TITLE
memory increase continuously while training!

### ISSUE THREAD

**Issue by sijun-zhou** [ildoonet/tf-pose-estimation#356]
Hi,
I have trained the code using mobilenet. Batch size is 24 on two GPUs. But I think my problem has noting to do with the GPUs. While training, the memory increases until reaches the consumption of the end of memory size. I have a 32G memory and 32G swap. But in the end, all of the swap and memory have been consumed! @ildoonet , @ouceduxzk have you met such problem while you training?

Thanks in advance!

**Comment by chrisskab** [comment]
@sijun-zhou Did you figure it out ?

**Comment by seovchinnikov** [comment]
I got the same. Take a look at tensorpack now

**Comment by ariel415el** [comment]
Same error here!
Happens only some of the times i run the train script

**Comment by ariel415el** [comment]
Same error here!
Happens only some of the times i run the train script

**Comment by ariel415el** [comment]
Same error here!
Happens only some of the times i run the train script
