### ISSUE TITLE
run with video is so bad

### ISSUE THREAD

**Issue by sunrise666** [ildoonet/tf-pose-estimation#362]
can you solve this problem?

**Comment by atyshka** [comment]
Not unless you describe it...

**Comment by siddrrsh** [comment]
<img width="1118" alt="Screen Shot 2019-08-01 at 10 38 11 AM" src="https://user-images.githubusercontent.com/31167704/62328730-b94de880-b468-11e9-8fcf-57dbd3d2b808.png">
