### ISSUE TITLE
mobilenet

### ISSUE THREAD

**Issue by wepter** [ildoonet/tf-pose-estimation#364]

**Comment by wepter** [comment]
Hi could you can provide us the  moblienet model  i cannot find this model in the demo thanks!

**Comment by BraginIvan** [comment]
Here are trained graph with MobileNet backbone. Checkpoint is not provided
https://github.com/ildoonet/tf-pose-estimation/tree/master/models/graph/mobilenet_thin

**Comment by DeeperDeeper** [comment]
@BraginIvan, What are the differences between these *.pb graphs, What are their corresponding configs in term of conv_depth and conv_depth2

**Comment by BraginIvan** [comment]
@DeeperDeeper The models (architecture and weights) are the same. The difference is the stage of optimization.  	
graph.pb is raw graph which includes unnecessary operations
graph_freeze.pb is inference graph (drop some nodes of graph which are not used for inference)
graph_opt.pb is inference graph with additional manual optimizations (fused batch norm, I don't actually remember what optimizations are applied)
