### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by Gouiaa** [ildoonet/tf-pose-estimation#368]
@ildoonet  Thanks for this great work. How could we train one of the models from scratch such as `MobileNetThin` ? Thanks

**Comment by BraginIvan** [comment]
You can find it here https://github.com/ildoonet/tf-pose-estimation/blob/master/etcs/training.md

**Comment by Gouiaa** [comment]
@BraginIvan  How to organize the coco dataset. I download it and put the files as follows:
`ls datasets/coco/images/
test2017 
train2017
val2017
ls datasets/coco/annotations/
all *.json files`

`python tf_pose/train.py --model=cmu --datapath=./datasets/coco --batchsize=64 --lr=0.001 --modelpath=./mymodels`

**I get an error FileNotFoundError: [Errno 2] No such file or directory: '/data/public/rw/coco/val2017/000000252219.jpg'**
The image is existed in val2017

**Comment by BraginIvan** [comment]
It also expects 
 parser.add_argument('--imgpath', type=str, default='/data/public/rw/coco/')
replace it with your path or add argument --imgpath=./datasets/coco/images

**Comment by BraginIvan** [comment]
also you may need to provide logging dir
 parser.add_argument('--logpath', type=str, default='/data/private/tf-openpose-log-2018-2/')
logpath is absolute path to somewhere

**Comment by Gouiaa** [comment]
@BraginIvan, I already fixed that. Thanks

**Comment by luckhhn** [comment]
@Gouiaa  Hello, I am a novice who just engaged in human body posture detection. I would like to ask you some questions about how to organize the coco data set and how to solve the problems you encounter.I am looking forward to your reply
