### ISSUE TITLE
Training coco stuck after started training

### ISSUE THREAD

**Issue by intvo** [ildoonet/tf-pose-estimation#371]
<img width="1229" alt="screen shot 2018-12-20 at 11 18 11 am" src="https://user-images.githubusercontent.com/40445787/50296724-1f8d7a00-0449-11e9-9234-387a29d1eece.png">

When I try to train coco dataset, it stops progressing after ` Training Started`
I'm using my Mac 2016 

Please let me know if you have any idea
Thank you

**Comment by tms2003** [comment]
it's running .just waiting with cpu 100% and gpu100%.....

**Comment by intvo** [comment]
ok thank you

**Comment by luckhhn** [comment]
@intvo Hello, I am a newcomer, and I also want to ask you about the training. I also want to train the mobilenetthin model from scratch, and then I don't know which data set should be downloaded. Here are 2014,2016 and 2017,And then, how do you organize these data sets and labels?Can you give me a detailed demonstration?

My environment is win10 1060ti

**Comment by filipetrocadoferreira** [comment]
I'm facing same problem with Tensorflow 1.13 (tf-nightly-gpu). It got stuck

**Comment by luckhhn** [comment]
@filipetrocadoferreira  Why did I report an error when I was training? I was very upset

**Comment by intvo** [comment]
@luckhhn Sorry for the delay in responding, we end up using OpenPose plus

**Comment by chrisskab** [comment]
@luckhhn Have you figured it out?

**Comment by ildoonet** [comment]
It seems like you have no gpu in your host machine... it will be very slow.
