### ISSUE TITLE
Creating new version of network_base Layers

### ISSUE THREAD

**Issue by Gouiaa** [ildoonet/tf-pose-estimation#375]
Hi,
Thanks for this great work. As Tensorflow 2.0 will appear soon and they will maybe remove some packages like contrib and slim. I want to change the Layers written in the code using slim package. I want to use the tf.keras.layers for better maintain the code. I think the most difficult part is It will not possible to use the pretrained weights because the keras graph will be different from the slim graph. Any suggestions?

**Comment by ildoonet** [comment]
We can parse slim graph files and convert it for keras version. Do you want to convert for keras version? If you do, please do Pull Requests.

**Comment by ildoonet** [comment]
Duplicated #391
