### ISSUE TITLE
I try to build "pafprocess module which is written in c++" 

### ISSUE THREAD

**Issue by mfurqaann** [ildoonet/tf-pose-estimation#385]
I try to build c++ library but when I try 
swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace
 
this is doesn't work like this
![image](https://user-images.githubusercontent.com/44994830/51720345-cfc15480-207f-11e9-83df-c806a2473b6a.png)

help me please
thanks

**Comment by ildoonet** [comment]
you are in wrong directory.
