### ISSUE TITLE
Not working with GPU.Giving low fps

### ISSUE THREAD

**Issue by TharinduRangana** [ildoonet/tf-pose-estimation#387]
Ignoring visible gpu device (device: 0, name: Tesla K40c, pci bus id: 0000:06:00.0, compute capability: 3.5) with Cuda compute capability 3.5. The minimum required Cuda capability is 3.7.

this was printed in cmd and giving low fps.

**Comment by ildoonet** [comment]
"The minimum required Cuda capability is 3.7."

you need to upgrade your cuda version.
