### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'mobilenet_thin_432'

### ISSUE THREAD

**Issue by gangubai** [ildoonet/tf-pose-estimation#393]
ak@Ak-Inspiron-3542:~/A_Projects/Seminar/tf-pose-estimation-master/tf_pose$ python3 pt3-webcam3D.py 
GLib-GIO-Message: 11:31:14.212: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Traceback (most recent call last):
  File "pt3-webcam3D.py", line 119, in <module>
    t = Terrain()
  File "pt3-webcam3D.py", line 49, in __init__
    w, h = model_wh(model)
  File "/home/ak/A_Projects/Seminar/tf-pose-estimation-master/tf_pose/networks.py", line 97, in model_wh
    width, height = map(int, resolution_str.split('x'))
ValueError: invalid literal for int() with base 10: 'mobilenet_thin_432'

**Comment by ildoonet** [comment]
model_wh function should get an argument like 432x368 (width x height), not model name.
