### ISSUE TITLE
Add download.bat file In win10

### ISSUE THREAD

**Issue by wadereye** [ildoonet/tf-pose-estimation#395]
Hi, I try this In win10.I found thedownload.sh can not work in win10 enviorment,
So I add a file download.bat ,this script file like that:

echo "In Windows 10 OS,Please download wget software :https://eternallybored.org/misc/wget/releases/wget-1.20-win64.zip"
echo "then,Unzip file to the path,And add path to your OS enviorment.like this: set f Path=%PATH%;d:\wget "
echo "[download] model graph : cmu"

# if you need, uncomment this.
# wget -c --tries=2  http://www.mediafire.com/file/1pyjsjl0p93x27c/graph_freeze.pb  -O ./graph_freeze.pb
#wget -c --tries=2 _url http://www.mediafire.com/file/i72ll9k5i7x6qfh/graph.pb  -O ./graph.pb
wget -c --tries=2  http://www.mediafire.com/file/qlzzr20mpocnpa3/graph_opt.pb  -O ./graph_opt.pb
echo "[download] end"

Can I share this file for others?

**Comment by ildoonet** [comment]
Sure. If you do pull-request, it would be better.
