### ISSUE TITLE
How to vizualize evolution of model with Tensorboard.

### ISSUE THREAD

**Issue by chrisskab** [ildoonet/tf-pose-estimation#398]
Hi, thank you for the good work.

I would like to train the mobilenet_thin model and see the eveolution of the loss and accuracy functions. Is there a way I can vizualise it in Tensorboard ? 

Thank you

**Comment by ariel415el** [comment]
tensorboard --logdir <path to logdir specified in train.py>
then open in browser the link given to you by tensorboard

Google would have probably solved that.

**Comment by chrisskab** [comment]
Thank you for your answer. 

Maybe my question was not clear: how do I generate the events during the training that will enable me to see the progression of the loss and accuracy function ?
Are there functions in the code already doing that or not ?

**Comment by ariel415el** [comment]
Yes, and the --logdir arguments controls their output directory
