### ISSUE TITLE
Output of the mobilenet graph vs output of the openpose graph

### ISSUE THREAD

**Issue by chrisskab** [ildoonet/tf-pose-estimation#403]
I vizualized the graph of the mobilenet_thin thanks to tensorboard.
I noticed that the graph is explicitely separated in two main parts: mobilenet and openpose.

Can someone tell me what is the role of both of them ? What are the output of both of them ?

**Comment by ildoonet** [comment]
mobilenet, which is base network, was used for feature extraction and predicting initial result. 

openpose, which is refinery layers, was for refine the result from mobilenet. 

If you see the original paper, they used vggnet for base network and then add some refinery layers.
