### ISSUE TITLE
testing problem: The system cannot find the path specified

### ISSUE THREAD

**Issue by pandailing** [ildoonet/tf-pose-estimation#41]
when i run the realtime_webcam.py with the instructed parameter, i got error that bassicly say like this:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./models\trained/mobilenet_368x368/model-release: Not found: FindFirstFile failed for: ./models/trained/mobilenet_368x368 : The system cannot find the path specified.

i search the folder and i also didnt find any ./models/trained/mobilenet_368x368 folder.
what i want to ask and maybe people with the same problem:
1. where is exactly the folder was? should i change the code itself?
2. i see a pretrained folder, is that the real folder?
3. the dataset is so big, co i couldnt try to train the data myself. got any alternatives?

**Comment by nuptwuchen** [comment]
hi, I meet the same question, and I try to solve it. However, when I mkdir the /models/trained/mobilenet_368x368/model-release , then  
python3 inference.py --model=mobilenet --imgpath=/home/wuchen/Downloads/tf-pose-estimation/images/golf.jpg

it goes wrong again, for help, thanks

DataLossError (see above for traceback): Unable to open table file ./models/trained/mobilenet_368x368/model-release: Failed precondition: models/trained/mobilenet_368x368/model-release: perhaps your file is in a different file format and you need to use a different restore operator?
