### ISSUE TITLE
Network structure update to CVPR 2018 version

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [ildoonet/tf-pose-estimation#423]
I noticed that your model structure is based on the [CVPR 2017 PAF paper](https://arxiv.org/abs/1611.08050) paper. But the[ CVPR 2018 PAF paper](https://arxiv.org/pdf/1812.08008.pdf) mentioned that 

>  We prove that PAF refinement is critical and sufficient for high accuracy, removing the body part confidence map refinement while increasing the network depth. This leads to a computationally faster and more accurate model

The model will definitely faster without confidence map refinement, but will it affect the performance? Especially when mobilenet are used as feature extractor. Do you have any suggestions on this or plans to do some experiment? 
__________
EDIT
__________
I modified the PAF structure according to 2018 PAF paper and currently training on single nvidia P4 GPU. I'll report the result when I'm done.
__________
EDIT2
__________
It turns out that this modification didn't improve the result much with light backbones like mobilenet. And the speed gain is limited. I'm switching to ResNet18/34/50 backbone now.

**Comment by ariel415el** [comment]
HI,
Can you share your changes to the repo in the meantime??

**Comment by ariel415el** [comment]
Can you share your changes to the repo in the meantime?

**Comment by ArtificialNotImbecile** [comment]
> Can you share your changes to the repo in the meantime?
The change I made is quite small(model in `mobilenet_thin.py` and loss in `train.py` and corresponding helper functions in `networks.py`). I've some ideas on how to improve the inference speed and I'll share some of them out when I get speed boost without too much accuracy loss(Actually I've already get 20-30 percent speed boost but with lower accuracy).  Also, I trained the model for 20 epochs and the `loss of last layer paf, heatmap = 55, 25`。Here are two examples I got from tensorboard:
![individualImage (3)](https://user-images.githubusercontent.com/10048576/55219830-debfb100-5240-11e9-8657-a6d3307eae84.png)
![individualImagen](https://user-images.githubusercontent.com/10048576/55219831-df584780-5240-11e9-8556-409fd9f5d012.png)
