### ISSUE TITLE
Video got no result

### ISSUE THREAD

**Issue by jinfagang** [ildoonet/tf-pose-estimation#425]
This is wired, the examples images all can detect except an video which contains images like this:

![image](https://user-images.githubusercontent.com/21303438/54908147-2e8d3800-4f22-11e9-8c7d-c4c92edf9918.png)

**Comment by jinfagang** [comment]
Detect separately using run.py can got result, but not when using run_video.py

![image](https://user-images.githubusercontent.com/21303438/54908274-7ad87800-4f22-11e9-9de7-3190a975970f.png)

**Comment by ShaocongZheng** [comment]
can u tell me how to solve this problem? 
i got the same problem!
thx a lot!

**Comment by leezhang2** [comment]
I got the same problem,I don't know how to solve this.

**Comment by Walid-Ahmed** [comment]
Me too  got the same problem

**Comment by israelpf** [comment]
Just add the following:

humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=args.resize_out_ratio)
