### ISSUE TITLE
opencv problem

### ISSUE THREAD

**Issue by NIEYALI** [ildoonet/tf-pose-estimation#43]
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Anybody meet this problem?
When I  run 'python3 inference.py --model=mobilenet --imgpath=...', I meet this problem.

**Comment by ouceduxzk** [comment]
probably your camera problem, since this error means the image is empty

**Comment by NIEYALI** [comment]
@ouceduxzk I don't use camera. Only test image. And I checked image path was right.

**Comment by xray1111** [comment]
I also meet this problem

**Comment by xray1111** [comment]
Sorry, my fault. I mis-typed the path name

**Comment by ildoonet** [comment]
The error message is saying that width, height information is missing.

Generally, your images are not decoded for some reason. Wrong path, wrong image, it can be anything. Please check your image path and the image is able to be decoded by opencv.
