### ISSUE TITLE
How to use body box

### ISSUE THREAD

**Issue by finnickniu** [ildoonet/tf-pose-estimation#439]
Hi @ildoonet 
I am wondering how to call the function  get_upper_body_box(img_w, img_h) under the class of Human in the estimator.py, since I want to use it to track human.

Regards,
Finn

**Comment by LawrenceXu13467** [comment]
Sorry if I did not understand your question correctly, but is this something you are looking for? 

Human.get_upper_body_box(w, h)?

**Comment by Finniu** [comment]
Hi @LawrenceXu13467
Yes，I want to use this box to track detected human, so I checked the estimator.py, and there is a function called get_upper_body_box(w, h), so I want to know how to use it.
Thanks

**Comment by finnickniu** [comment]
Try:
`e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
humans = e.inference(image)
b_boxs=humans.get_upper_body_box(w, h)`
Change the threshold in estimator to 0.1, the code will work.

**Comment by YangFanYaoNa** [comment]
How about "get_face_box()"?I called this function,but I couldn't get  the right box.

**Comment by YangFanYaoNa** [comment]
I have understood

**Comment by thekhieu** [comment]
@YangFanYaoNa  @finnickniu  how to get it? can you tell me about that?

**Comment by YangFanYaoNa** [comment]
e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
humans = e.inference(image)
face_boxs=humans.get_face_box()(w, h)
