### ISSUE TITLE
In transform & __coco_vecs, is neck missing?

### ISSUE THREAD

**Issue by LawrenceXu13467** [ildoonet/tf-pose-estimation#445]
This question is based on a closed issue: https://github.com/ildoonet/tf-pose-estimation/issues/211

In the original coco order, we have the following body parts in the .json file, right?

["nose","left_eye","right_eye","left_ear","right_ear","left_shoulder","right_shoulder","left_elbow","right_elbow","left_wrist","right_wrist","left_hip","right_hip","left_knee","right_knee","left_ankle","right_ankle"]

However, there are only 17 parts here in the above list (Neck and Background missing).
And in OpenPose Order, we have 19 parts
    Nose = 0
    Neck = 1
    RShoulder = 2
    RElbow = 3
    RWrist = 4
    LShoulder = 5
    LElbow = 6
    LWrist = 7
    RHip = 8
    RKnee = 9
    RAnkle = 10
    LHip = 11
    LKnee = 12
    LAnkle = 13
    REye = 14
    LEye = 15
    REar = 16
    LEar = 17
    Background = 18

Let's say we do not consider Background for the time being. Still, how are we going to map all 18 body parts (in openpose order) to 17 body parts ( in coco order)?

Thanks.

**Comment by finnickniu** [comment]
Hi @LawrenceXu13467,
The neck position is estimated by point 2 and 5, check here [https://github.com/ildoonet/tf-pose-estimation/issues/159#issuecomment-386995024](url).

**Comment by LawrenceXu13467** [comment]
Very helpful. Thank you!
