### ISSUE TITLE
Matplotlib Backend error

### ISSUE THREAD

**Issue by adampelah** [ildoonet/tf-pose-estimation#469]
Hi, am getting this error when running the demo:

 UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

I have set matplotlib.use('TkAgg') in run.py, but to no avail. Not sure what else to do.

All help appreciated.

**Comment by rudra3pratap3** [comment]
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
plt.show()   
please resolve my prob

**Comment by henbucuoshanghai** [comment]
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

**Comment by Guo-king** [comment]
I have solved this problem by using 'pip install PyQt5'.
