### ISSUE TITLE
VIDEOIO ERROR: V4L: can't open camera by index 0 Traceback (most recent call last):   File "run_webcam.py", line 45, in <module>     logger.info('cam image=%dx%d' % (image.shape[1], image.shape[0])) AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Shitiz1708** [ildoonet/tf-pose-estimation#472]
When i run the run.py on google colab , this error occurs.
please help

**Comment by kimdwkimdw** [comment]
You cannot use camera on google colab in usual way.

Checkout https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=2viqYx97hPMi
