### ISSUE TITLE
Where is run.py or run_webcam.py ?

### ISSUE THREAD

**Issue by zubairahmed-ai** [ildoonet/tf-pose-estimation#48]
You said that we can use these files for demo but I am not able to find them, even in the other repo, how to view live webcam demo for this?

**Comment by elmuz** [comment]
They're in 'src' folder...

**Comment by ildoonet** [comment]
@zubairahmed-ai @elmuz is correct.

**Comment by zubairahmed-ai** [comment]
Thanks both of you, I managed to run it
