### ISSUE TITLE
Joint Coordinates

### ISSUE THREAD

**Issue by oguzhankarabulut** [ildoonet/tf-pose-estimation#49]
Hello, how can i print joints coordinates ?

**Comment by jrod4404** [comment]
I have the same question as well.  Must be possible right?

**Comment by ildoonet** [comment]
@oguzhankarabulut @jrod4404 

https://github.com/ildoonet/tf-pose-estimation#python-usage

You can get 'humans' instance which include joints of persons. If you look at it, you will know.
