### ISSUE TITLE
failed using tensorrt on tx2

### ISSUE THREAD

**Issue by willfu** [ildoonet/tf-pose-estimation#497]
after installation on tx2, I found the default fps is quite low, about 5 fps, much lower than the one shown on readme. 
I just use $ python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=1 .

while I use $ python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=1 --tensorrt=True, it reports error as below:

will@will-desktop:~/tf-pose-estimation$ python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=1 --tensorrt=True
2019-08-11 18:03:18.585491: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-08-11 18:03:30.661049: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
WARNING: Logging before flag parsing goes to stderr.
W0811 18:03:30.744550 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/mobilenet/mobilenet.py:369: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

[2019-08-11 18:03:35,496] [TfPoseEstimator-WebCam] [DEBUG] initialization mobilenet_thin : /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb
I0811 18:03:35.496699 547506102288 run_webcam.py:42] initialization mobilenet_thin : /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb
[2019-08-11 18:03:35,498] [TfPoseEstimator] [INFO] loading graph from /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
I0811 18:03:35.498320 547506102288 estimator.py:310] loading graph from /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
W0811 18:03:35.499779 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/estimator.py:311: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0811 18:03:35.500979 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/estimator.py:312: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "run_webcam.py", line 45, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h), trt_bool=str2bool(args.tensorrt))
  File "/home/will/tf-pose-estimation/tf_pose/estimator.py", line 327, in __init__
    use_calibration=True,
TypeError: create_inference_graph() got an unexpected keyword argument 'use_calibration'

could someone tell me why it reports error? thanks.

**Comment by willfu** [comment]
it should be the tensorflow 1.14.0 compatible issue. I will look into the details.

**Comment by errno-mmd** [comment]
tensorflow.contrib.tensorrt.create_inference_graph() seems to no longer support 'use_calibration' argument.
https://github.com/tensorflow/tensorflow/commit/2590dc34ca3ad61e29e5d098eb3cd44e2861c91d#diff-c9068b7e53b77bdcfe37dff6a4be8b58

In the older version (e.g. Tensorflow 1.13.1), the default of use_calibration was True. So, there is no need to specify use_calibration=True.

I think simply removing the 'use_calibration=True' argument is a reasonable solution.

**Comment by willfu** [comment]
thanks.
