### ISSUE TITLE
No module named 'tensorpack.dataflow.prefetch'

### ISSUE THREAD

**Issue by IversonSun** [ildoonet/tf-pose-estimation#50]
I failed to train with COCO dataset. Images are in path '/home/dl/tf-pose-estimation/train2017'.

```
$ cd /home/dl/tf-pose-estimation
$ python3 train.py --model=cmu --datapath=/home/dl/tf-pose-estimation/annotations --imgpath=/home/dl/tf-pose-estimation/ --batchsize=64 --lr=0.001 --modelpath=/home/dl/tf-pose-estimation/models/mydl/cmu/
```

and get error:

Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from pose_dataset import get_dataflow_batch, DataFlowToQueue, CocoPose
  File "/home/dl/tf-pose-estimation/src/pose_dataset.py", line 27, in <module>
    from tensorpack.dataflow.prefetch import PrefetchData
ImportError: No module named 'tensorpack.dataflow.prefetch'

anyone know how to fix it?

**Comment by ouceduxzk** [comment]
install tensorpack then

**Comment by IversonSun** [comment]
@ouceduxzk thx for your reply. 
Actually I can import tensorpack and tensorpack.dataflow successfully in python3, but when I try to import tensorpack.dataflow.prefetch , the same error occurs. I am using tensorpack 0.8.0, I will try to find whether the problem is about the version of tensorpack.

**Comment by IversonSun** [comment]
I just check the repo of tensorpack, and find that 'prefetch.py' has been renamed to 'parallel.py', after modify
`import tensorpack.dataflow.prefetch`
to
`import tensorpack.dataflow.parallel`
in pose_dataset.py, then this problem solved. now I am trying to solve other problems haha.

**Comment by yw155** [comment]
Hi @IversonSun , I also meet the same problem, but I modify it and meet a new problem, which is "AttributeError: Can't pickle local object 'MapDataComponent.__init__.<locals>.f'". This problem is also occurred in pose_dataset.py. Do you have meet the same problem?

**Comment by IversonSun** [comment]
I haven't met such a problem, maybe you can try older version. I am working with the commit of Jan 30, 2018. btw, I am using Ubuntu 16.04, only inference works on Windows, train on Windows will not work.

**Comment by IversonSun** [comment]
@yw155 I haven't met such a problem, maybe you can try older version. I am working with the commit of Jan 30, 2018. btw, I am using Ubuntu 16.04, only inference works on Windows, train on Windows will not work.
