### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'

### ISSUE THREAD

**Issue by zkumar** [ildoonet/tf-pose-estimation#510]
while running 
python run_webcam.py --camera walking.mp4
from tf_pose.estimator import TfPoseEstimator
File "D:\Vijay\Pose Estimation\tf_pose\estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'

**Comment by zkumar** [comment]
Additional details
   I have a virtual environment where I have installed latest tensoflow-gpu (1.14.0) using pip command. I have followed the process as per documentation for for installing 
Cuda 10.1
cDNN 7.5
TensorRT 5.1.5
Tensorflow GPU 1.14

I have changed **import tensorflow.contrib.tensorrt** as trt to
**from tensorflow.python.compiler.tensorrt import trt_convert as trt**

but I am getting following error

ImportError: cannot import name 'tensorrt' from 'tensorflow.python.compiler' (C:\Users\AIKAKI\Anaconda3\envs\openCV\lib\site-packages\tensorflow\python\compiler\__init__.py)

I also checked the site-package and don't any file named tensorRT etc. 

When I checked a mirror repo, I see the file

https://git.codingcafe.org/Mirrors/tensorflow/tensorflow/tree/bdb5c9a16f84cfe3909568ae91a0315937909811/tensorflow/python/compiler/tensorrt

how do we solve this problem?

**Comment by caiya55** [comment]
I get the same problem in tf12.0-gpu, I use the old version code, and it works now. I think the trt is the new part, in the old version code, there is no trt.

**Comment by zkumar** [comment]
I see no releases in the repo. How did you get old code? Please guide me. Also which TF version you are using it to run? any Cuda and cudnn version dependencies?

**Comment by caiya55** [comment]
I use tf-gpu 12.0. I found the repo that I downloaded in my PC. I found it is different from this repo, I downloaded it from here about 2 months before. You can download them from other fork. (Maybe my fork). You can check the old fork that there is no tenorrt lib imported.

**Comment by zkumar** [comment]
It finally worked for me. I have taken commit code before tensor RT changes.  Thanks for help.

**Comment by Tony1868388** [comment]
how to solve this problem  detail to me ,thanks

**Comment by errno-mmd** [comment]
You can download an older code from this repository.
https://stackoverflow.com/questions/13636559/how-to-download-zip-from-github-for-a-particular-commit-sha

It seems this is the latest archive before TensorRT was enabled.
https://github.com/ildoonet/tf-pose-estimation/archive/111a6ef06368bb8906f12e5b2dfa17aa553fd2f6.zip

**Comment by errno-mmd** [comment]
But I recommend a solution below.

On my repository, I modified estimator.py to handle ModuleNotFoundError.
See https://github.com/errno-mmd/tf-pose-estimation/commit/dfdee60fde73ecf87aa36dd3bdc582925036352b

It disables tensorrt option if TensorRT is not available.

**Comment by chuanenlin** [comment]
I solved it simply by going to \tf-pose\estimator.py and commenting out `import tensorflow.contrib.tensorrt as trt`.
