### ISSUE TITLE
Did anyone know how to save the video output ?(save the video results)

### ISSUE THREAD

**Issue by Byronnar** [ildoonet/tf-pose-estimation#519]
I have write a script,but it does not work.
import argparse
import logging
import time

import cv2
import numpy as np

from tf_pose.estimator import TfPoseEstimator
from tf_pose.networks import get_graph_path, model_wh

logger = logging.getLogger('TfPoseEstimator-Video')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

fps_time = 0

if name == 'main':
parser = argparse.ArgumentParser(description='tf-pose-estimation Video')
parser.add_argument('--video', type=str, default='')
parser.add_argument('--write_video', type=str, default='')
parser.add_argument('--resolution', type=str, default='432x368', help='network input resolution. default=432x368')
parser.add_argument('--model', type=str, default='mobilenet_thin', help='cmu / mobilenet_thin')
parser.add_argument('--show-process', type=bool, default=False,
help='for debug purpose, if enabled, speed for inference is dropped.')
parser.add_argument('--showBG', type=str, default='', help='Use it with any non-empty string to show skeleton only.')
args = parser.parse_args()

logger.debug('initialization %s : %s' % (args.model, get_graph_path(args.model)))
w, h = model_wh(args.resolution)
if w > 0 and h > 0:
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
else:
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368))
logger.debug('video read+')
cap = cv2.VideoCapture(args.video)
if args.write_video:
    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    out = cv2.VideoWriter(args.write_video,fourcc, 20.0, (432,368))
#     #out = cv2.VideoWriter(output_path, video_FourCC, video_fps, video_size)
ret_val, image = cap.read()

logger.info('cap image=%dx%d' % (image.shape[1], image.shape[0]))

if cap.isOpened() is False:
    print("Error opening video stream or file")
while cap.isOpened():
    ret_val, image = cap.read()

    #humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=4.0)
    # print(image)
    humans = e.inference(image, resize_to_default=True, upsample_size=4.0)
    if args.showBG:
        image = np.zeros(image.shape, dtype=np.uint8)
    image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False)

    cv2.putText(image, "FPS: %f" % (1.0 / (time.time() - fps_time)), (10, 10),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    if args.write_video:
        out.write(image)
    else:
        cv2.imshow('tf-pose-estimation result', image)

    fps_time = time.time()
    if cv2.waitKey(1) == 27:
        break
cap.release()
out.release()
cv2.destroyAllWindows()
logger.debug('finished+')

But it does not work:
Traceback (most recent call last):
File "run_video_save.py", line 62, in 
humans = e.inference(image, resize_to_default=True, upsample_size=4.0)
File "/home/byronnar/pyprojects/cv/tf-pose-estimation/tf_pose/estimator.py", line 537, in inference
raise Exception('The image is not valid. Please check your image exists.')
Exception: The image is not valid. Please check your image exists.

Have anyone can help me? Thanks

**Comment by mohitjeste** [comment]
Did you come to know how to save it?

**Comment by TheGreatLeoX** [comment]
Hi, I had the same error report.

I enter,
`python newvideo2.py --video=./etcs/dance.mp4 --write_video=./save_test/video/1.mp4`
and get the report,

```
Traceback (most recent call last): 
    File "newvideo2.py", line 55, in <module>
    humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=4.0)
  File "/sdb/tmp/users/xiongja/tf-pose-estimation-master/tf_pose/estimator.py", line 537, in inference
    raise Exception('The image is not valid. Please check your image exists.')
Exception: The image is not valid. Please check your image exists.
```

Have you solved this problem?

**Comment by mohitjeste** [comment]
This is my draw_humans functions in estimator.py which is successfully giving output 


`def draw_humans(npimg, humans, imgcopy=False):
        if imgcopy:
            npimg = np.copy(npimg)
        image_h, image_w = npimg.shape[:2]
        centers = {}
        for human in humans:
            # draw point
            for i in range(common.CocoPart.Background.value):
                if i not in human.body_parts.keys():
                    continue

                body_part = human.body_parts[i]
                center = (int(body_part.x * image_w + 0.5), int(body_part.y * image_h + 0.5))
                centers[i] = center
                cv2.circle(npimg, center, 3, common.CocoColors[i], thickness=3, lineType=8, shift=0)
                
            # draw line
            for pair_order, pair in enumerate(common.CocoPairsRender):
                if pair[0] not in human.body_parts.keys() or pair[1] not in human.body_parts.keys():
                    continue

                # npimg = cv2.line(npimg, centers[pair[0]], centers[pair[1]], common.CocoColors[pair_order], 3)
                cv2.line(npimg, centers[pair[0]], centers[pair[1]], common.CocoColors[pair_order], 3)
                
            
        return npimg`
