### ISSUE TITLE
Dropbox have a download limit for free account

### ISSUE THREAD

**Issue by ildoonet** [ildoonet/tf-pose-estimation#52]
I'm trying to find an another free cloud which offers much higher limitations.

Any suggestions?

**Comment by khaerulumam42** [comment]
google drive maybe. What size of the model is?

**Comment by ildoonet** [comment]
@khaerulumam42 10~500MB. There are many people who can not download models since dropbox have daily limits.

**Comment by mzx5464** [comment]
So where could i get these files now ? @ildoonet

**Comment by hluoaf** [comment]
These files could not be downloaded from dropbox until now. So where could I get these files? Maybe you could take google drive or one drive into consideration.

**Comment by khaerulumam42** [comment]
I was uploaded to my google drive account, and this is the link https://drive.google.com/drive/folders/13gMsQCBPvgUf8XEJ9gQrAhACZySUjCb5?usp=sharing

**Comment by world4jason** [comment]
mega.nz might be a good substitution?

**Comment by mzx5464** [comment]
I'm very sorry for that I accidentally deleted a file, could you upload it again?
Thank you very much for this @khaerulumam42

**Comment by ildoonet** [comment]
@khaerulumam42 Thanks for you help. Does google drive have a limit for daily download? If not, I will upload models from now on.

**Comment by world4jason** [comment]
@ildoonet Google drive also have that limitation, but we can make a copy to our place and bypass the limit.

FYI : https://www.ampercent.com/bypass-google-drive-download-limit/13333/

**Comment by prasoonmayank** [comment]
Hi there
The download is still not working. The folder shared on the drive is empty.
Kindly resolve the issue. Mega.nz is the best option since, it has unlimited free downloads.

**Comment by jax79sg** [comment]
Hi,

Can consider moving the files onto the bit-torrent network. @ildoonet can start by using utorrent to generate a link and starting an initial seed. The rest of us can help by seeding it further by using his link. The caveat is that we need to avoid identical filenames.

**Comment by elmuz** [comment]
I think some university may block torrent traffic, so maybe keeping a google drive-like download option active would be better.

**Comment by ildoonet** [comment]
I've just uploaded files on MediaFire which offers unlimited downloads(as far as I know)

You should pull from github and try download them.

**Comment by sreyaschaithanya** [comment]
Thanks a lot for sharing the links.. But the links don't work in bash script though. It just downloads the meta data. You'll have to go to the link and then download to get the complete file.

**Comment by khaerulumam42** [comment]
Thank you @world4jason , you all can access again the link on my google drive, I re-uploaded the models.

**Comment by ildoonet** [comment]
Thanks everyone.
