### ISSUE TITLE
run.py

### ISSUE THREAD

**Issue by khaledosama999** [ildoonet/tf-pose-estimation#53]
how can i use different version of the mobile net model (fast ,accurate)

**Comment by khaerulumam42** [comment]
while you type in command prompt or terminal to run run.py, set --model=<your model>.
example :` `python run.py --model=mobilenet_thin_432x368 --camera=0``. You must have downloaded the models

**Comment by elmuz** [comment]
The only one you can use is the mobilenet_thin_432x368. 'fast' and 'accurate' need to trained, unless you have some weighted model.
