### ISSUE TITLE
was trying to install -r requirements.txt for openpose

### ISSUE THREAD

**Issue by rashiAg122** [ildoonet/tf-pose-estimation#545]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-m7qqlh6h\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-m7qqlh6h\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-install-m7qqlh6h\matplotlib\pip-egg-info'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-m7qqlh6h\matplotlib\
    Complete output (26 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pip-install-m7qqlh6h\matplotlib\setup.py", line 258, in <module>
        with open('lib/matplotlib/mpl-data/matplotlibrc', 'w') as fd:
    PermissionError: [Errno 13] Permission denied: 'lib/matplotlib/mpl-data/matplotlibrc'
    ================================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
      matplotlib: yes [3.1.1]
          python: yes [3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC
                      v.1916 32 bit (Intel)]]
        platform: yes [win32]

    OPTIONAL SUBPACKAGES
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
             agg: yes [installing]
           tkagg: yes [installing; run-time loading from Python Tcl/Tk]
          macosx: no  [Mac OS-X only]

    OPTIONAL PACKAGE DATA
            dlls: no  [skipping due to configuration]

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by khan958** [comment]
@rashiAg122  Just try to install individual by pip command.

**Comment by rashiAg122** [comment]
@khan958 I did that, but it is showing an error of the file not found, but the file is present in there
