### ISSUE TITLE
why last layer in each stage has Relu=false

### ISSUE THREAD

**Issue by ouceduxzk** [ildoonet/tf-pose-estimation#55]
Hi @ildoonet , thanks for sharing your code, while playing with the architecture, i found that cmu-pose originally use relu=true while in your case its false for the last conv layer in each stage,  is there any reason to do that  ? or it's simply performing well with relu=false

**Comment by ildoonet** [comment]
@ouceduxzk If you change it as 'relu=true', it performs in the same manner.

Because outputs of the network is 'score map' which have values 0~1. 

So, minus values(<0) can be considered as zeros.

----
PS. I tried with tanh, it performs better with small margin.

**Comment by ouceduxzk** [comment]
@ildoonet  that makes sense, thanks for the explanation, also I found that mobilenet which is on 92x92 feature map works better in terms of heatmap plot, that makes sense since is has higher resolution, though the loss is > 1000, which makes sense due to the way loss is calculated
