### ISSUE TITLE
Has anyone succeeded transforming mobilenet_v2_small pb file into tflite?

### ISSUE THREAD

**Issue by khg2478** [ildoonet/tf-pose-estimation#556]
Hi.

I have tried to convert stored pb file of mobilenet_v2_small into tflite but it doesn't work properly.

I've read related issues here and found a previous issue reported as mine (https://github.com/ildoonet/tf-pose-estimation/issues/490).

I see many people struggle for this process.

Has anybody done it?? Otherwise I might have to spend some time to figure this out for myself.

Thanks.

**Comment by bsherifi** [comment]
@khg2478 Hi, I am recently struggling with this step myself. I have converted graph_freeze.pb to tflite but all it crashes when I run it on my device and when I output the result from an image using Python, I get some very inaccurate output. Considering that you wrote this on December 3rd, you may have figured it out so if you could help please let me know. 

Thank you in return.

**Comment by khg2478** [comment]
> @khg2478 Hi, I am recently struggling with this step myself. I have converted graph_freeze.pb to tflite but all it crashes when I run it on my device and when I output the result from an image using Python, I get some very inaccurate output. Considering that you wrote this on December 3rd, you may have figured it out so if you could help please let me know.
> 
> Thank you in return.

Hi. Unfortunately, I was not able to. I think it should have been related with tensorflow version issues. If you solve the problem, I hope you can leave a solution here too.
