### ISSUE TITLE
no outputs when running scripts

### ISSUE THREAD

**Issue by marisna** [ildoonet/tf-pose-estimation#557]
Hi, 
I'm trying to test your repo.
After troubles with tf version, finally everything seems ok and running properly (layers initialized, no import error).
However, i still can't get visuals outputs : 
- when launching run.py, i dont get the estimaton writing on the image,
- when launching run_video.py, i cant nor visualize anything and terminal outputs me "cannot connect to X server" 

Is anyone faced the problem or have suggestion?

**Comment by waelausy** [comment]
Hello,
When you run the 'run.py' you must add a line to save the prediction image.
So add this command
`plt.savefig('images/output.png')`
after the line 85 of the file run.py
https://github.com/ildoonet/tf-pose-estimation/blob/9aaf34708e9863eeab9685a7ec52a45f3b576e2d/run.py#L85
Hope this helps

**Comment by marisna** [comment]
Hi, thanks a lot for answering.
Actually I tried it, thanks to your specifications I tried again at the line you mentionned. 
No images was saved.
Actually, I noticed that the problem is deeper : any of the modifications I made on the script got effect.. Should have a deep look to it. 
I'll close this issue. 
Thanks again !
