### ISSUE TITLE
Please HELP!!  A problem about using the cmu model: graph.pb

### ISSUE THREAD

**Issue by starry-night-0** [ildoonet/tf-pose-estimation#582]
Hello everyone! Please give me some help! I try to use the cmu model and I download the graph.pb, I put it in graph/cmu/graph.pb, and I modify the garph_path like this:

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='tf-pose-estimation run')  
    parser.add_argument('--image', type=str, default='./images/p3_dance.png')  
    _**parser.add_argument('--model', type=str, default='cmu',
                        help='cmu / mobilenet_thin / mobilenet_v2_large / mobilenet_v2_small')**_
……

def get_graph_path(model_name): 
    dyn_graph_path = {
        # 'cmu': 'graph/cmu/graph_opt.pb',
        **_'cmu': 'graph/cmu/graph.pb',_**
        'openpose_quantize': 'graph/cmu/graph_opt_q.pb',
        'mobilenet_thin': 'graph/mobilenet_thin/graph_opt.pb',
        'mobilenet_v2_large': 'graph/mobilenet_v2_large/graph_opt.pb',
        'mobilenet_v2_large_r0.5': 'graph/mobilenet_v2_large/graph_r0.5_opt.pb',
        'mobilenet_v2_large_quantize': 'graph/mobilenet_v2_large/graph_opt_q.pb',
        'mobilenet_v2_small': 'graph/mobilenet_v2_small/graph_opt.pb',
    }
……

but when I run the run.py, it has an error:
**_" graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message"_**

what should I do to solve this problem? Could someone give me some help? Thanks a lot.

**Comment by leo7r** [comment]
@starry-night-0 did you manage to solve this issue?
