### ISSUE TITLE
wants to train own data 

### ISSUE THREAD

**Issue by burhanuddin78** [ildoonet/tf-pose-estimation#583]
I have to train my own classifier that detects various human activities such as standing, running, etc. The question is how can I build my own classifier. Any guidance would be helpful

**Comment by a726** [comment]
> I have to train my own classifier that detects various human activities such as standing, running, etc. The question is how can I build my own classifier. Any guidance would be helpful

hi, can you know how to train own data? I need your help!

**Comment by burhanuddin78** [comment]
yes, I know I will help you burhanuddin5023@gmail.com
