### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by prasoonmayank** [ildoonet/tf-pose-estimation#60]
Hi there
The download.sh file inside models/graph/cmu_640x360 and inside models/graph/cmu_640x480 is not working, and the links give the error: 
ERROR 429: Too many requests.

Please resolve the issue.

**Comment by hiankun** [comment]
@prasoonmayank It's due to the daily limitation of Dropbox. Issue https://github.com/ildoonet/tf-pose-estimation/issues/52 are talking about this.

**Comment by ildoonet** [comment]
@prasoonmayank @hiankun 

Duplicated Issue #52.
