### ISSUE TITLE
Maximum person limit

### ISSUE THREAD

**Issue by bharatm11** [ildoonet/tf-pose-estimation#607]
- Is there a limit on the number of persons that we can detect?

- Is there a way to limit this? Would reducing the maximum number of persons to 1 help speed up processing?

**Comment by FragrantRye** [comment]
- no.

- You can simply choose the person with the highest score. But this won't bring any performance improvement.

**Comment by knife216** [comment]
> * no.
> * You can simply choose the person with the highest score. But this won't bring any performance improvement.

Hello，
I want to know how to select only one person because I don't need multiple person functions.

Thanks

**Comment by MuxiJ** [comment]
> > * no.
> > * You can simply choose the person with the highest score. But this won't bring any performance improvement.
> 
> Hello，
> I want to know how to select only one person because I don't need multiple person functions.
> 
> Thanks

do u know how to select only one person now?
