### ISSUE TITLE
Malloc error when running run_webcam.py

### ISSUE THREAD

**Issue by guxiao0822** [ildoonet/tf-pose-estimation#62]
Hi,

I met with a problem. When I tried to run it in the terminal, it always crashed. But when I ran the offline demo, it worked. The error is listed below.

------------------------------------------
guxiaodeMacBook-Pro:tf-openpose shawn$ python3 ./src/run_webcam.py --model=mobilenet_thin_432x368 --camera=0
python3(1979,0x7fff7437c000) malloc: *** error for object 0x1128fa3e8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
-----------------------------------------
My MBP:
Processor 2.2GHz Intel Core i7
Memory 16GB
Graphics Intel Iris Pro 

Is there any method to fix it?
Thanks a lot!

**Comment by ildoonet** [comment]
Can you run the script 'run_webcam.py' line by line? I guess there are many posibilities..

**Comment by guxiao0822** [comment]
Thanks,
the following sentence caused the problem,
**from networks import get_graph_path, model_wh**

**Comment by helloworld** [comment]
Is there any fix to this? Receiving the same error.

**Comment by guxiao0822** [comment]
Not yet.

 

发件人: bounces+848413-a4e7-gux14=fudan.edu.cn@sgmail.github.com <bounces+848413-a4e7-gux14=fudan.edu.cn@sgmail.github.com> 代表 Sashank Thupukari
发送时间: 24 March 2018 14:54
收件人: ildoonet/tf-pose-estimation <tf-pose-estimation@noreply.github.com>
抄送: Xiao GU <gux14@fudan.edu.cn>; Author <author@noreply.github.com>
主题: Re: [ildoonet/tf-pose-estimation] Malloc error when running run_webcam.py (#62)

 

Is there any fix to this? Receiving the same error.

**Comment by ichizero** [comment]
The same error occured in "run_webcam.py" and "run_video.py".

```
src $ python run_webcam.py --model=mobilenet_thin --resolution=432x368 --camera=0
python(13152,0x7fffad7fc380) malloc: *** error for object 0x11a6da3e8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

In my environment, I added "import common" to "run_webcam.py" and "run_video.py", so it worked!
