### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Amyhds** [ildoonet/tf-pose-estimation#664]
[ WARN:0] global /tmp/easy_install-_vmuyn79/opencv-python-4.4.0.46/opencv/modules/videoio/src/cap_gstreamer.cpp (1761) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global /tmp/easy_install-_vmuyn79/opencv-python-4.4.0.46/opencv/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /tmp/easy_install-_vmuyn79/opencv-python-4.4.0.46/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global /tmp/easy_install-_vmuyn79/opencv-python-4.4.0.46/opencv/modules/videoio/src/cap_v4l.cpp (1004) tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Traceback (most recent call last):
  File "run_webcam.py", line 51, in <module>
    logger.info('cam image=%dx%d' % (image.shape[1], image.shape[0]))
AttributeError: 'NoneType' object has no attribute 'shape'

이런 에러가 뜨는데 어떡하나요? 이미지는 잘 돌아가는데 웹캠이 안됩니다...
I got these errors but I don't know how to handle this issues...how to solve this?
It runs well with test images(run.py) but doesn't work with run_webcam.py

**Comment by insidedctm** [comment]
This is probably an OpenCV issue with reading from your webcam. In line 50 of run_webcam.py what is the value of ret_val? It should be True, if not your webcam is not being read by OpenCV.

**Comment by Amyhds** [comment]
In fact, my jetpack is 4.3 so I downloaded opencv 3.4.0 
I think this caused the problem. I'll find the solution. Thank you for your comment!

**Comment by fengjiufa** [comment]
Hello, I solved this problem. In general, there are two reasons: the first is to ensure that your video file path is not wrong, and the second is that the opencv you installed is not compatible, you can try：
conda remove opencv
conda update conda

conda install --channel menpo opencv
或者选择下面的OpenCV 3.1版本 :
conda install -c menpo opencv3
pip install --upgrade pip
pip install opencv-contrib-python

**Comment by Amyhds** [comment]
I can't install anaconda for some reasons but i'll try your solution by another way! thank you!
