### ISSUE TITLE
ImportError: cannot import name '_pafprocess'

### ISSUE THREAD

**Issue by ArimaValanImmanuel** [ildoonet/tf-pose-estimation#668]
```
Traceback (most recent call last):
  File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\estimator.py", line 17, in <module>
    from tf_pose.pafprocess import pafprocess
  File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\pafprocess\pafprocess.py", line 13, in <module>
    from . import _pafprocess
ImportError: cannot import name '_pafprocess'
```

performed all steps in Readme.md correctly, but still the same error

**Comment by ArimaValanImmanuel** [comment]
> ```
> Traceback (most recent call last):
>   File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
>     from tf_pose.runner import infer, Estimator, get_estimator
>   File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
>     from tf_pose import eval
>   File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
>     from tf_pose.estimator import TfPoseEstimator
>   File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\estimator.py", line 17, in <module>
>     from tf_pose.pafprocess import pafprocess
>   File "A:\Arima\PROJECTS\Pose Estimation\tf-pose-estimation-master\tf_pose\pafprocess\pafprocess.py", line 13, in <module>
>     from . import _pafprocess
> ImportError: cannot import name '_pafprocess'
> ```
> 
> performed all steps in Readme.md correctly, but still the same error

@ildoonet

**Comment by insidedctm** [comment]
Did you install using 'Package Installation' or the manual install that requires to run 'swig'.

If Package Install then you should have an executable file within site-packages/tf-pose... . When I install on Ubuntu I have this file: `/home/ubuntu/anaconda3/lib/python3.7/site-packages/tf_pose-0.1.1-py3.7-linux-x86_64.egg/_pafprocess.cpython-37m-x86_64-linux-gnu.so`. It looks like you are on Windows so the naming will be different but it will have _pafprocess in the name and (presumably) a .dll extension.

If Manual Install then it probably failed either in the compile or the link stage. Try re-running the swig command and posting the output here.

**Comment by ArimaValanImmanuel** [comment]
Actually the file exists but still the same error, that's the issue. 😞😐 @insidedctm

**Comment by insidedctm** [comment]
You are on Windows right? What is the name of the file and the full path? Have you tried the manual install route?

**Comment by insidedctm** [comment]
Also worth looking at this https://github.com/ildoonet/tf-pose-estimation/issues/609

**Comment by ArimaValanImmanuel** [comment]
> You are on Windows right? What is the name of the file and the full path? Have you tried the manual install route?

![git issue pic 2](https://user-images.githubusercontent.com/35724936/106102699-c3d46580-6165-11eb-8ab1-acb847084340.PNG)
![git issue pic 1](https://user-images.githubusercontent.com/35724936/106102702-c5059280-6165-11eb-8a3b-57c98e14604f.PNG)

_pafprocess.cp38-win_amd64.pyd

**Comment by ArimaValanImmanuel** [comment]
> Also worth looking at this #609

actually executed that command too

**Comment by ArimaValanImmanuel** [comment]
> Also worth looking at this #609

![git issue pic 3](https://user-images.githubusercontent.com/35724936/106164677-43872200-61b0-11eb-820d-4d11546043e4.PNG)
![git issue pic 4](https://user-images.githubusercontent.com/35724936/106164680-44b84f00-61b0-11eb-81b8-235ef06b831d.PNG)

**Comment by insidedctm** [comment]
Not sure what the cause of this problem is. It looks like the _pafprocess module has been built successfully but it's not being loaded by python.

**Comment by ArimaValanImmanuel** [comment]
> Not sure what the cause of this problem is. It looks like the _pafprocess module has been built successfully but it's not being loaded by python.

sir but my only hope is git, please help me, or give me alternative, or tell me where i can learn to build my own posenet
Kindly

**Comment by ArimaValanImmanuel** [comment]
I uninstalled conda and somehow magically now things work

I want to thank @insidedctm who has supported me and helped me till now, thank you sir!

I'm closing this issue now

**Comment by insidedctm** [comment]
> I uninstalled conda and somehow magically now things work
> 
> I want to thank @insidedctm who has supported me and helped me till now, thank you sir!
> 
> I'm closing this issue now

👍🏻
