### ISSUE TITLE
The new version is slower than old version

### ISSUE THREAD

**Issue by segatecm** [ildoonet/tf-pose-estimation#68]
I had get the old version about one month ago. And I use the realtime camera demo, by cmu model. it is about 15 FPS. My gpu is Titan1080.

Today I download the new version and new graph cmu_640x360. But the FPS is only 10.
I compare the code, the network_cmu.py file had nothing changed. 
So please tell me why the new code slower then 50%. 
thank ! @ildoonet

**Comment by ildoonet** [comment]
@segatecm Since new graph have a input size of '640x360' which is larger than the previous one, '368x368'

(640*360)/(368*368) = 1.7x

So the bottom line is, the reason is that the new network graph has wider architecture. 

But I will investigate on this to find any posibilities to improve more.

**Comment by ildoonet** [comment]
@segatecm I add some codes to use dynamic input sizes. You can now use cmu's model with different input size like 368x368.

**Comment by segatecm** [comment]
Thanks ildoonet! And I have a question, is the cmu model trained by yourself?
