### ISSUE TITLE
help on retrain using cmu model

### ISSUE THREAD

**Issue by Minotaur-CN** [ildoonet/tf-pose-estimation#7]
Dear ildoonet,
@ildoonet 
I follow your training.md, but the training precedure was stacked during step=3000, and the GPU usage is droped to 0%.

Please help me sovle this proble?
Ps. the loss is increasing during the training precedure!

**Comment by ildoonet** [comment]
@Minotaur-CN 

In my case, the loss is decreased and gpu utilization is at almost 100%. 

Can you try again and if you have a problem again, please write your status with hardware specs and command lines you use.

**Comment by andyqian2015** [comment]
Hi @Minotaur-CN ,@ildoonet,what parameter do you choose,when you retrain the model of cmu?I retrain the Model as the trainning.md tell. the only difference is the batchsize setted to 16. but after iter of 10000,the loss is still 1000 more or less. I just don't know why, can you give me some clue?

**Comment by ildoonet** [comment]
@andyqian2015 I updated training.md, See : https://github.com/ildoonet/tf-pose-estimation/blob/master/etcs/training.md

Also I attached loss graphs. It is bit tricky to train properly.
