### ISSUE TITLE
Does the optimization of graph work?

### ISSUE THREAD

**Issue by ztwe** [ildoonet/tf-pose-estimation#71]
I find that the graph_freeze.pb and  graph_opt.pb of CMU model are both 209MB, and the speeds are almost the same. It seems  the optimization of graph doesn't work.
@ildoonet

**Comment by ildoonet** [comment]
@ztwe It is not necessary to reduce graph file when you use optimization script provided by tensorflow. For optimized graph of mobilenet versions, their sizes are reduced compared to the frozen graph.
