### ISSUE TITLE
Unable to parse graph files

### ISSUE THREAD

**Issue by worthlessFella** [ildoonet/tf-pose-estimation#72]
I am unable to parse cmu 480 .pb files, either through script or through tensor-board. To confirm my setup is correct I have tried mobilenet graphs an it works. 
![image](https://user-images.githubusercontent.com/23638491/35703691-eb301f58-0794-11e8-8a18-de3e7bc815ea.png)

graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by ouceduxzk** [comment]
from my experience, you need to parse the freeze model or the opt model

**Comment by ildoonet** [comment]
@ouceduxzk is right. Freeze the graph before you use it.

**Comment by luckhhn** [comment]
@ouceduxzk  sir ，  i want to know how to parse the freeze model or the opt model ，thank you very much
