### ISSUE TITLE
cmu_640x380 vs openpose accuracy

### ISSUE THREAD

**Issue by makeitraina** [ildoonet/tf-pose-estimation#80]
I tested cmu_640x380 and openpose on a few simple images. The images are 512x288 and I ran openpose at that resolution as well. I found the cmu_640x380 model is much less accurate at labeling the key points correctly.

Is the cmu_640x380 model expected to perform as well the openpose model in this scenario or are there different parameters I can train the tensorflow model with to achieve higher accuracy?

**Comment by ildoonet** [comment]
@makeitraina Well, I guess that is mainly because of the multi-scale prediction. Openpose predicts a single image with multiple patches. 

I will put this issue on my next project to reproduce openpose result when CMU's original weights are used.

**Comment by ildoonet** [comment]
it is duplicated #26.
