### ISSUE TITLE
Unable to transform_graph on frozen model: FeedInputs: unable to find feed output image:0

### ISSUE THREAD

**Issue by ssq6** [ildoonet/tf-pose-estimation#85]
I trained a mobilenet_thin model with checkpoint model-160000 and dumped the graph with write_graph named trained_graph.pbtxt.
I was also able to successfully run 
python3 -m tensorflow.python.tools.freeze_graph \
  --input_graph=.../trained_graph.pbtxt \
  --output_graph=.../frozen.model-160000 \
  --input_checkpoint=.../model-160000 \
  --output_node_names="Openpose/concat_stage7"
to get a frozen graph frozen.model-160000

But when I tried to run optimzation with:
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
    --in_graph=.../frozen.model-160000 \
    --out_graph=.../opt.model-160000 \
    --inputs='image:0' \
    --outputs='Openpose/concat_stage7:0' \
    --transforms='
    strip_unused_nodes(type=float, shape="1,368,368,3")
    remove_nodes(op=Identity, op=CheckNumerics)
    fold_constants(ignoreError=False)
    fold_old_batch_norms
    fold_batch_norms'

it gave me the following error:
 tensorflow/tools/graph_transforms/transform_graph.cc:210] FeedInputs: unable to find feed output image:0

When I run optimization on the unfrozen graph, it works.
Any ideas on why I am hitting this error please?

**Comment by ildoonet** [comment]
@ssq6 I guess your graph file is broken. You can save the graph file using 'run_checkpoint.py' script.

**Comment by ssq6** [comment]
Yes, that was the problem, solved with run_checkpoint dumped graph. Thanks @ildoonet!

**Comment by memesi** [comment]
@ssq6 Could you successfully run your model after freezing it ? And see its predictions on images ?
