### ISSUE TITLE
Graph File not found

### ISSUE THREAD

**Issue by electroncatcher** [ildoonet/tf-pose-estimation#89]
/home/mgnad/.conda/envs/OpenposeTF) mgnad@ubuntu:~/tf-openpose/src$ python3 run.py --model=mobilenet_thin --resolution=432x368 --image=...
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))
  File "/home/mgnad/tf-openpose/src/networks.py", line 77, in get_graph_path
    raise Exception('Graph file doesn\'t exist, path=%s' % graph_path)
**Exception: Graph file doesn't exist, path=./models/graph/mobilenet_thin/graph_opt.pb**

Please help if anyone know the solution.

**Comment by ildoonet** [comment]
run in tf-openpose folder. The path is relative.

**Comment by ildoonet** [comment]
@electroncatcher Close this issue if you solve this problem.

**Comment by electroncatcher** [comment]
I had run the code in the tf-openpose folder itself, but didn't work. Anyway I tried on windows and everything was fine. The vmware ubuntu gave me this error.

**Comment by todd95** [comment]
$ cd models/graph/cmu
$ bash download.sh
