### ISSUE TITLE
How to train with another network structure?

### ISSUE THREAD

**Issue by yw155** [ildoonet/tf-pose-estimation#92]
Hi @ildoonet , I would like to train the codes with another network structure, e.g., resnet, but I don't know how to start. I already write a network definition file like to 'network_cmu' and add it to the source codes. I select the 'openpose_coco.npy' as the pretrained model to initialize the network. When I run the train.py, there is an error occurred at the function of 'load' in network_base.py, which said '**Shape of a new variable (Mconv5_stage5_L2/weights) must be fully defined, but instead was unknown.**' Actually, in my network definition file, there is no layer of 'Mconv5_stage5_L2'. So how can I do in the next step?

**Comment by ildoonet** [comment]
@yw155 You need to initialize the network with a proper weight file. As you select resnet architecture as a base network, you need to initialize it with pretrain resnet weights. The error you met means that your weight file is not matched with the architecture. 

Or, you can initialize it with random values.

**Comment by yw155** [comment]
Thanks.
