### ISSUE TITLE
Does anybody have frozen accurate 1.0 model ?

### ISSUE THREAD

**Issue by seovchinnikov** [ildoonet/tf-pose-estimation#95]
Hey guys!
Does anybody have frozen TF accurate 1.0 trained model (pb) ?

Thank you

**Comment by ildoonet** [comment]
@seovchinnikov The accurate version is somewhat better than others but its performance is not enough. So I am trying to train new models with difference architectures and different modules. I will update if I get any improvements.

**Comment by seovchinnikov** [comment]
Hey @ildoonet!
Thank you!
'By perfomance' - do you mean the speed or accuracy ?
Anyway, I'm interested in comparing relative speed/accuracy of different mobilenet/cmu models.

**Comment by ildoonet** [comment]
@seovchinnikov In the above context, it means 'accuracy'. I have a plan to benchmark on public datasets like coco. If you want to, you can write some codes to evaluate the performance, and send me a pull request. 👍

**Comment by seovchinnikov** [comment]
Thank you,
I'll do it as soon as I have free time,
right now I need something slightly better than 0.75 model but my GPU for training is on the way :(
