### ISSUE TITLE
pip3 install AST error

### ISSUE THREAD

**Issue by yw155** [ildoonet/tf-pose-estimation#96]
Hi @ildoonet, when I install AST from 'requirements.txt', I get the following error:
pip3 install ast
Collecting ast
  Using cached AST-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0bb8rt8h/ast/setup.py", line 6, in <module>
        README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
      File "/usr/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-0bb8rt8h/ast/AST/README'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0bb8rt8h/ast/

Do you know how to solve this problem?
Thanks.

**Comment by ildoonet** [comment]
@yw155 ast is included in python3. So you can skip the installation for AST.
