### ISSUE TITLE
Can I use mobile_net model commercially?

### ISSUE THREAD

**Issue by ryhe** [ildoonet/tf-pose-estimation#97]
I'm newbie about ML and Tensorflow.
Because of it, I can not understand below line.
> Some of them are below and checkpoint files are provided for research purpose.

Is checkpoint files `models/graph/mobilenet_thin/*`?
Please tell me what checkpoint files means in this context.

Thanks,

**Comment by ildoonet** [comment]
@ryhe You can use modes for only research purposes. Contact us if you want to use it commercially.
