### ISSUE TITLE
About the number of 'step_per_epoch'

### ISSUE THREAD

**Issue by yw155** [ildoonet/tf-pose-estimation#99]
Hi @ildoonet, I see there is a variable 'step_per_epoch' in train.py, which equals to divide 121745 by mini-batch size.  The number of 121745 should be the number of training set of COCO. But I import COCO-2017 and find that there are only 118287 images. So I would like to ask this number is correct? Should I change this number?
Thanks.

**Comment by ildoonet** [comment]
@yw155 That number is maybe incorrect. I think your value is correct.
